# ==============================================================================
# Toroloom — Terraform State Backend Bootstrap — Outputs
# ==============================================================================

output "state_bucket_name" {
  description = "S3 bucket name for Terraform state"
  value       = aws_s3_bucket.terraform_state.id
}

output "lock_table_name" {
  description = "DynamoDB table name for Terraform state locking"
  value       = aws_dynamodb_table.terraform_locks.name
}

output "bucket_policy_json" {
  description = "JSON of the applied S3 bucket policy (for audit/verification)"
  value       = data.aws_iam_policy_document.terraform_state.json
  sensitive   = false
}

output "lock_table_policy_json" {
  description = "JSON of the applied DynamoDB resource policy (for audit/verification)"
  value       = length(var.allowed_iam_principals) > 0 ? data.aws_iam_policy_document.terraform_locks[0].json : "null (no resource policy — relying on IAM identity-based policies)"
  sensitive   = false
}

output "state_s3_uri" {
  description = "S3 URI for the state bucket"
  value       = "s3://${aws_s3_bucket.terraform_state.id}"
}

output "storage_alarm_name" {
  description = "Name of the S3 bucket size CloudWatch alarm"
  value       = try(aws_cloudwatch_metric_alarm.state_bucket_size[0].alarm_name, "not created (create_storage_alarm = false)")
}

output "backend_config_command" {
  description = "Command to initialize the parent Terraform module with remote state"
  value       = <<-EOF
terraform init -backend-config="bucket=${aws_s3_bucket.terraform_state.id}" \
               -backend-config="key=rds/terraform.tfstate" \
               -backend-config="region=${var.aws_region}" \
               -backend-config="dynamodb_table=${aws_dynamodb_table.terraform_locks.name}" \
               -backend-config="encrypt=true"
EOF
}

output "backend_hcl_content" {
  description = "Contents for terraform/backend.hcl (paste into that file)"
  value       = <<-EOF
# backend.hcl — generated by terraform/bootstrap
# Usage: terraform init -backend-config=backend.hcl

bucket         = "${aws_s3_bucket.terraform_state.id}"
key            = "rds/terraform.tfstate"
region         = "${var.aws_region}"
dynamodb_table = "${aws_dynamodb_table.terraform_locks.name}"
encrypt        = true
EOF
}
