// =============================================================================
// Toroloom — Financial Glossary
// 100+ financial terms with categories, definitions, and cross-references
// =============================================================================

import { GlossaryTerm } from '../types';

export const glossaryTerms: GlossaryTerm[] = [
  // ═══════════════════ EQUITY ═══════════════════
  {
    id: 'equity',
    term: 'Equity',
    shortDefinition: 'Ownership in a company represented by shares.',
    detailedDefinition: `Equity represents ownership interest in a company. When you buy equity shares of a company, you become a partial owner and are entitled to a portion of its profits (dividends) and assets. Equity is considered a high-risk, high-return asset class and is ideal for long-term wealth creation. In India, equity investments held for more than 12 months qualify as long-term capital gains (LTCG).`,
    category: 'Equity',
    example: 'Ravi bought equity shares of Reliance Industries to become a part-owner of the company.',
    tags: ['shares', 'stocks', 'ownership', 'capital'],
    icon: '📈',
    relatedTerms: ['shares', 'dividend', 'market-cap', 'ipo'],
  },
  {
    id: 'shares',
    term: 'Shares',
    shortDefinition: 'Units of ownership in a company.',
    detailedDefinition: `Shares are the smallest units of a company's capital. When a company divides its ownership into small units, each unit is called a share. Shareholders are entitled to dividends, voting rights, and a portion of the company's residual assets in case of liquidation. Shares can be listed on stock exchanges for public trading.`,
    category: 'Equity',
    example: 'TCS has over 36 crore shares outstanding, each representing a tiny piece of the company.',
    tags: ['stocks', 'equity', 'ownership', 'unit'],
    icon: '📄',
    relatedTerms: ['equity', 'dividend', 'stock-split', 'bonus-shares'],
  },
  {
    id: 'blue-chip',
    term: 'Blue Chip',
    shortDefinition: 'Large, well-established, financially stable companies.',
    detailedDefinition: `Blue chip stocks refer to shares of large, reputable, and financially sound companies with a history of reliable performance. These companies are usually market leaders in their sectors, have strong balance sheets, and consistently pay dividends. Examples in India include Reliance, TCS, HDFC Bank, and Infosys. Blue chip stocks are considered lower-risk investments within the equity category.`,
    category: 'Equity',
    example: 'Investors consider HDFC Bank a blue chip stock due to its consistent growth and dividend payments.',
    tags: ['large-cap', 'stable', 'reliable', 'top-company'],
    icon: '🔵',
    relatedTerms: ['large-cap', 'dividend', 'market-cap'],
  },
  {
    id: 'market-cap',
    term: 'Market Capitalization (Market Cap)',
    shortDefinition: 'Total value of a company\'s outstanding shares.',
    detailedDefinition: `Market capitalization is calculated by multiplying a company's current stock price by its total number of outstanding shares. It represents the total market value of a company. Companies are categorized as large-cap (top 100), mid-cap (101st to 250th), and small-cap (251st onwards) based on their market cap. Market cap helps investors understand a company's size and risk profile.`,
    category: 'Equity',
    example: 'If a company has 10 crore shares trading at ₹500 each, its market cap is ₹5,000 crore.',
    tags: ['valuation', 'size', 'large-cap', 'mid-cap', 'small-cap'],
    icon: '🏢',
    relatedTerms: ['blue-chip', 'large-cap', 'small-cap'],
  },
  {
    id: 'large-cap',
    term: 'Large Cap',
    shortDefinition: 'Top 100 companies by market capitalization.',
    detailedDefinition: `Large-cap companies are the 100 largest companies listed on Indian stock exchanges by market capitalization. These are typically well-established, stable businesses with a proven track record. Large-cap stocks are considered less volatile and safer than mid-cap or small-cap stocks. Many blue chip companies fall under the large-cap category.`,
    category: 'Equity',
    example: 'Reliance Industries, TCS, and HDFC Bank are examples of large-cap companies.',
    tags: ['big', 'stable', 'safe', 'top-100'],
    icon: '🏛️',
    relatedTerms: ['market-cap', 'blue-chip', 'mid-cap', 'small-cap'],
  },
  {
    id: 'mid-cap',
    term: 'Mid Cap',
    shortDefinition: 'Companies ranked 101st to 250th by market cap.',
    detailedDefinition: `Mid-cap companies are those ranked between 101st and 250th in terms of market capitalization on Indian stock exchanges. These companies are usually in a growth phase, offering higher growth potential than large caps but with higher risk. Mid-cap stocks can be excellent wealth creators over the long term but may experience higher volatility.`,
    category: 'Equity',
    example: 'Many emerging sector leaders like Tata Elxsi and Coforge are mid-cap companies.',
    tags: ['growth', 'medium', 'emerging'],
    icon: '📊',
    relatedTerms: ['market-cap', 'large-cap', 'small-cap'],
  },
  {
    id: 'small-cap',
    term: 'Small Cap',
    shortDefinition: 'Companies ranked 251st and below by market cap.',
    detailedDefinition: `Small-cap companies are those ranked 251st and below in market capitalization on Indian stock exchanges. These are typically younger, smaller companies with high growth potential but also higher risk and volatility. Small-cap stocks can provide multi-bagger returns but require careful research and a higher risk tolerance.`,
    category: 'Equity',
    example: 'Many innovative startups and niche players are classified as small-cap companies.',
    tags: ['high-growth', 'risky', 'volatile', 'multi-bagger'],
    icon: '🚀',
    relatedTerms: ['market-cap', 'large-cap', 'mid-cap'],
  },
  {
    id: 'stock-split',
    term: 'Stock Split',
    shortDefinition: 'Dividing existing shares into multiple shares to reduce price.',
    detailedDefinition: `A stock split is a corporate action where a company divides its existing shares into multiple shares to reduce the trading price per share. For example, in a 2:1 split, each shareholder gets 2 shares for every 1 share they owned, but the total value remains the same. Stock splits make shares more affordable for retail investors and increase liquidity.`,
    category: 'Equity',
    example: 'If a ₹10,000 stock undergoes a 5:1 split, you get 5 shares worth ₹2,000 each.',
    tags: ['corporate-action', 'affordability', 'liquidity'],
    icon: '✂️',
    relatedTerms: ['bonus-shares', 'buyback'],
  },
  {
    id: 'bonus-shares',
    term: 'Bonus Shares',
    shortDefinition: 'Free additional shares given to existing shareholders.',
    detailedDefinition: `Bonus shares are additional shares given to existing shareholders without any cost, based on their current holdings. Companies issue bonus shares from their accumulated profits or reserves. While the number of shares increases, the total investment value remains the same as the stock price adjusts proportionally. Bonus shares reward shareholders without requiring cash outlay.`,
    category: 'Equity',
    example: 'In a 1:1 bonus issue, you get 1 free share for every 1 share you hold.',
    tags: ['free-shares', 'corporate-action', 'reward'],
    icon: '🎁',
    relatedTerms: ['stock-split', 'dividend'],
  },
  {
    id: 'buyback',
    term: 'Buyback',
    shortDefinition: 'Company purchases its own shares from shareholders.',
    detailedDefinition: `A buyback (or share repurchase) is when a company buys back its own shares from existing shareholders. This reduces the number of outstanding shares, which can increase earnings per share (EPS) and shareholder value. Buybacks signal management's confidence in the company and are often seen as a tax-efficient way to return cash to shareholders compared to dividends.`,
    category: 'Equity',
    example: 'Infosys announced a ₹9,300 crore buyback, offering shareholders ₹1,850 per share.',
    tags: ['repurchase', 'corporate-action', 'value'],
    icon: '🔄',
    relatedTerms: ['dividend', 'eps'],
  },

  // ═══════════════════ DERIVATIVES ═══════════════════
  {
    id: 'derivatives',
    term: 'Derivatives',
    shortDefinition: 'Financial instruments whose value derives from an underlying asset.',
    detailedDefinition: `Derivatives are financial contracts whose value is derived from the price movement of an underlying asset such as stocks, indices, commodities, or currencies. The two main types are Futures and Options. Derivatives are used for hedging (protecting against price movements) and speculation (profiting from price movements). In India, derivatives are traded on the NSE and BSE.`,
    category: 'Derivatives',
    example: 'A farmer uses wheat futures to lock in a price for his harvest, hedging against price drops.',
    tags: ['futures', 'options', 'hedging', 'speculation'],
    icon: '📐',
    relatedTerms: ['futures', 'options', 'hedging'],
  },
  {
    id: 'futures',
    term: 'Futures',
    shortDefinition: 'Contract to buy/sell an asset at a predetermined price on a future date.',
    detailedDefinition: `A futures contract is a standardized agreement to buy or sell an underlying asset at a predetermined price on a specified future date. Futures are exchange-traded and have standardized lot sizes and expiry dates. They are used for hedging and speculation. Unlike options, both parties in a futures contract are obligated to fulfill the contract at expiry. Futures trading requires margin money.`,
    category: 'Derivatives',
    example: 'A trader buys Nifty 50 futures at 22,500, expecting the index to rise by expiry.',
    tags: ['forward', 'contract', 'margin', 'leverage'],
    icon: '📅',
    relatedTerms: ['derivatives', 'options', 'margin', 'hedging'],
  },
  {
    id: 'options',
    term: 'Options',
    shortDefinition: 'Contract giving the right (but not obligation) to buy/sell an asset.',
    detailedDefinition: `Options are derivative contracts that give the buyer the right, but not the obligation, to buy (Call option) or sell (Put option) an underlying asset at a predetermined price (strike price) on or before a specific date (expiry). Options come in two types: Call (CE) for bullish views and Put (PE) for bearish views. The buyer pays a premium for this right. Options offer defined risk (limited to premium) with potentially unlimited profit.`,
    category: 'Derivatives',
    example: 'Buying a ₹24,000 Nifty Call option for ₹150 premium — if Nifty rises above ₹24,150 by expiry, you profit.',
    tags: ['call', 'put', 'premium', 'strike', 'expiry'],
    icon: '🎯',
    relatedTerms: ['derivatives', 'futures', 'call-option', 'put-option', 'premium'],
  },
  {
    id: 'call-option',
    term: 'Call Option',
    shortDefinition: 'Option to buy an asset at a fixed price within a specific timeframe.',
    detailedDefinition: `A Call Option (CE) gives the buyer the right to buy the underlying asset at the strike price before or on expiry. Call options are purchased when the buyer expects the asset price to rise significantly. The profit is unlimited (as price can rise indefinitely), while the maximum loss is limited to the premium paid.`,
    category: 'Derivatives',
    example: 'Buying a ₹2,500 Reliance Call option for ₹50 — if Reliance reaches ₹2,600, the call option becomes profitable.',
    tags: ['ce', 'bullish', 'buy', 'right'],
    icon: '⬆️',
    relatedTerms: ['options', 'put-option', 'premium', 'strike-price'],
  },
  {
    id: 'put-option',
    term: 'Put Option',
    shortDefinition: 'Option to sell an asset at a fixed price within a specific timeframe.',
    detailedDefinition: `A Put Option (PE) gives the buyer the right to sell the underlying asset at the strike price before or on expiry. Put options are purchased when the buyer expects the asset price to fall significantly. The profit is maximized when the asset price falls to zero, while the maximum loss is limited to the premium paid.`,
    category: 'Derivatives',
    example: 'Buying a ₹22,000 Nifty Put option for ₹100 — if Nifty falls below ₹21,900 by expiry, you profit.',
    tags: ['pe', 'bearish', 'sell', 'right'],
    icon: '⬇️',
    relatedTerms: ['options', 'call-option', 'premium', 'strike-price'],
  },
  {
    id: 'premium',
    term: 'Premium',
    shortDefinition: 'The price paid to buy an options contract.',
    detailedDefinition: `Premium is the price an option buyer pays to the option seller (writer) to acquire the rights conferred by the option. Several factors affect premium: the underlying asset's price, strike price, time to expiry, volatility, interest rates, and dividends. The premium consists of intrinsic value (real value if exercised now) and time value (potential future value).`,
    category: 'Derivatives',
    example: 'If a Nifty 24,500 Call is trading at ₹150, then ₹150 is the premium per share (one lot = 50 shares, so total premium = ₹7,500).',
    tags: ['price', 'cost', 'intrinsic-value', 'time-value'],
    icon: '💎',
    relatedTerms: ['options', 'call-option', 'put-option', 'intrinsic-value', 'time-decay'],
  },
  {
    id: 'strike-price',
    term: 'Strike Price',
    shortDefinition: 'The predetermined price at which an option can be exercised.',
    detailedDefinition: `The strike price (also called exercise price) is the fixed price at which the underlying asset can be bought (Call) or sold (Put) when the option is exercised. Options are classified as In-The-Money (ITM), At-The-Money (ATM), or Out-Of-The-Money (OTM) based on the relationship between the strike price and the current market price of the underlying asset.`,
    category: 'Derivatives',
    example: 'In a Reliance 2,500 Call option, ₹2,500 is the strike price at which you can buy Reliance shares.',
    tags: ['exercise-price', 'itm', 'atm', 'otm'],
    icon: '🎯',
    relatedTerms: ['options', 'call-option', 'put-option'],
  },
  {
    id: 'expiry',
    term: 'Expiry',
    shortDefinition: 'The last day on which an options/futures contract is valid.',
    detailedDefinition: `Expiry is the final day on which a derivatives contract can be exercised or traded. In India, equity derivatives expire on the last Thursday of every month. Weekly expiries also exist for popular indices like Nifty, Bank Nifty, and Fin Nifty. After expiry, all open positions are settled automatically — futures are cash-settled, and options expire worthless if out-of-the-money.`,
    category: 'Derivatives',
    example: 'The monthly Nifty expiry is on the last Thursday of the month at 3:30 PM.',
    tags: ['settlement', 'last-day', 'thursday'],
    icon: '⏰',
    relatedTerms: ['options', 'futures', 'settlement'],
  },
  {
    id: 'hedging',
    term: 'Hedging',
    shortDefinition: 'Protecting an investment from adverse price movements.',
    detailedDefinition: `Hedging is a risk management strategy where an investor takes an offsetting position in a related security to reduce the risk of adverse price movements. Common hedging strategies include buying put options to protect a stock portfolio or using futures to lock in prices. While hedging reduces risk, it also limits potential profits. It is like buying insurance for your investments.`,
    category: 'Derivatives',
    example: 'A mutual fund manager buys Nifty Put options to protect the portfolio from a market crash.',
    tags: ['protection', 'insurance', 'risk-management'],
    icon: '🛡️',
    relatedTerms: ['derivatives', 'options', 'futures', 'risk-management'],
  },
  {
    id: 'open-interest',
    term: 'Open Interest (OI)',
    shortDefinition: 'Total number of outstanding derivative contracts not yet settled.',
    detailedDefinition: `Open Interest (OI) represents the total number of outstanding futures or options contracts that have not been closed or settled. Unlike trading volume (which counts all trades), OI counts only open positions. Rising OI indicates new money flowing into the market and confirms the current trend. Falling OI suggests the trend is losing strength. OI analysis is a key tool for derivatives traders.`,
    category: 'Derivatives',
    example: 'If Nifty futures OI increases from 10 lakh to 12 lakh contracts while price rises, it confirms bullish momentum.',
    tags: ['oi', 'volume', 'position', 'analysis'],
    icon: '📊',
    relatedTerms: ['futures', 'options', 'volume'],
  },

  // ═══════════════════ MUTUAL FUNDS ═══════════════════
  {
    id: 'mutual-fund',
    term: 'Mutual Fund',
    shortDefinition: 'A pool of money collected from many investors to invest in securities.',
    detailedDefinition: `A mutual fund is a financial vehicle that pools money from multiple investors to invest in a diversified portfolio of stocks, bonds, or other securities. Professional fund managers manage the portfolio. Investors own units that represent a portion of the fund's holdings. Mutual funds offer diversification, professional management, and affordability for retail investors.`,
    category: 'Mutual Funds',
    example: 'Ravi invests ₹5,000/month in an HDFC Mutual Fund that invests in top Indian companies.',
    tags: ['mf', 'investment', 'portfolio', 'diversification'],
    icon: '💰',
    relatedTerms: ['sip', 'nav', 'expense-ratio', 'index-fund'],
  },
  {
    id: 'nav',
    term: 'Net Asset Value (NAV)',
    shortDefinition: 'Per-unit market value of a mutual fund.',
    detailedDefinition: `Net Asset Value (NAV) is the price per unit of a mutual fund. It is calculated by dividing the total value of all assets in the fund (minus liabilities) by the total number of outstanding units. NAV changes daily based on the market performance of the fund's underlying investments. When you buy or sell mutual fund units, the transaction happens at the NAV price.`,
    category: 'Mutual Funds',
    example: 'If a mutual fund has assets worth ₹100 crore and 5 crore units, its NAV is ₹20.',
    tags: ['price', 'valuation', 'unit'],
    icon: '💵',
    relatedTerms: ['mutual-fund', 'sip'],
  },
  {
    id: 'sip',
    term: 'Systematic Investment Plan (SIP)',
    shortDefinition: 'A regular, fixed-amount investment in a mutual fund.',
    detailedDefinition: `SIP (Systematic Investment Plan) is an investment method where you invest a fixed amount regularly (monthly, quarterly) in a mutual fund. SIPs leverage the power of compounding and rupee cost averaging — you buy more units when the market is low and fewer when it is high. SIPs are ideal for long-term wealth creation and starting with as little as ₹500 per month.`,
    category: 'Mutual Funds',
    example: 'Starting a ₹10,000 monthly SIP in an index fund at age 25 can grow to over ₹3 crore by retirement.',
    tags: ['regular', 'investment', 'rupee-cost-averaging', 'compounding'],
    icon: '📅',
    relatedTerms: ['mutual-fund', 'nav', 'compounding'],
  },
  {
    id: 'expense-ratio',
    term: 'Expense Ratio',
    shortDefinition: 'Annual fee charged by a mutual fund for managing your investment.',
    detailedDefinition: `The expense ratio is the annual fee that a mutual fund charges to manage your money. It includes management fees, administrative costs, and other operational expenses. Expressed as a percentage of the fund's average assets, a lower expense ratio means the fund is more cost-efficient. Index funds and ETFs typically have very low expense ratios (0.1-0.5%) compared to active funds (1-2%).`,
    category: 'Mutual Funds',
    example: 'A fund with a 1.5% expense ratio charges ₹1,500 annually on an investment of ₹1,00,000.',
    tags: ['fee', 'cost', 'management-fee', 'ter'],
    icon: '📋',
    relatedTerms: ['mutual-fund', 'index-fund', 'etf'],
  },
  {
    id: 'index-fund',
    term: 'Index Fund',
    shortDefinition: 'A mutual fund that tracks a market index like Nifty 50.',
    detailedDefinition: `An index fund is a type of mutual fund that aims to replicate the performance of a specific market index, such as the Nifty 50 or Sensex. Instead of trying to beat the market, index funds simply buy all stocks in the index in the same proportion. They have lower expense ratios than actively managed funds and offer broad market exposure.`,
    category: 'Mutual Funds',
    example: 'A Nifty 50 index fund buys all 50 Nifty stocks in the same proportion as the index.',
    tags: ['passive', 'tracker', 'low-cost', 'nifty'],
    icon: '📊',
    relatedTerms: ['mutual-fund', 'expense-ratio', 'etf'],
  },
  {
    id: 'etf',
    term: 'Exchange Traded Fund (ETF)',
    shortDefinition: 'A marketable security that tracks an index and trades like a stock.',
    detailedDefinition: `An ETF (Exchange Traded Fund) is a type of investment fund that holds a basket of securities (stocks, bonds, etc.) and trades on stock exchanges like individual stocks. Unlike mutual funds that are bought/sold at NAV at day-end, ETFs can be bought/sold throughout the trading day at market prices. ETFs combine the diversification of mutual funds with the flexibility of stock trading, usually with very low expense ratios.`,
    category: 'Mutual Funds',
    example: 'Buying 10 units of Nippon India ETF Nifty 50 gives you exposure to all 50 Nifty companies.',
    tags: ['exchange-traded', 'passive', 'low-cost', 'liquid'],
    icon: '📈',
    relatedTerms: ['index-fund', 'mutual-fund', 'expense-ratio', 'nav'],
  },
  {
    id: 'aum',
    term: 'Assets Under Management (AUM)',
    shortDefinition: 'Total market value of investments managed by a fund.',
    detailedDefinition: `Assets Under Management (AUM) is the total market value of all investments and assets managed by a mutual fund, fund house, or financial institution. A larger AUM generally indicates investor confidence and institutional stability. However, very large AUM can sometimes make it challenging for a fund manager to deploy capital effectively without impacting market prices.`,
    category: 'Mutual Funds',
    example: 'SBI Mutual Fund has an AUM of over ₹8 lakh crore, making it India\'s largest fund house.',
    tags: ['size', 'managed', 'fund-size'],
    icon: '🏦',
    relatedTerms: ['mutual-fund', 'expense-ratio'],
  },

  // ═══════════════════ TECHNICAL ANALYSIS ═══════════════════
  {
    id: 'technical-analysis',
    term: 'Technical Analysis',
    shortDefinition: 'Analyzing price patterns and volumes to forecast future prices.',
    detailedDefinition: `Technical analysis is the study of market action through charts and statistical indicators to forecast future price movements. It is based on three principles: market discounts everything, prices move in trends, and history tends to repeat itself. Technical analysts use tools like moving averages, RSI, MACD, support/resistance levels, and candlestick patterns to make trading decisions.`,
    category: 'Technical Analysis',
    example: 'A trader notices a \"Head and Shoulders\" pattern forming on the Nifty chart and predicts a reversal.',
    tags: ['chart', 'analysis', 'trading', 'patterns'],
    icon: '📉',
    relatedTerms: ['moving-average', 'rsi', 'macd', 'support-resistance'],
  },
  {
    id: 'support-resistance',
    term: 'Support & Resistance',
    shortDefinition: 'Price levels where a trend tends to pause or reverse.',
    detailedDefinition: `Support is a price level where buying interest is strong enough to prevent the price from falling further. Resistance is a price level where selling pressure prevents the price from rising further. These levels are identified from historical price data and are key tools in technical analysis. When a support or resistance level is broken decisively, they often reverse roles — resistance becomes support and vice versa.`,
    category: 'Technical Analysis',
    example: 'Nifty has bounced from 22,000 (support) three times — traders place buy orders near this level.',
    tags: ['levels', 's-r', 'breakout', 'chart'],
    icon: '📏',
    relatedTerms: ['technical-analysis', 'moving-average', 'breakout'],
  },
  {
    id: 'moving-average',
    term: 'Moving Average (MA)',
    shortDefinition: 'Average price over a specific period, used to identify trends.',
    detailedDefinition: `A Moving Average (MA) is a widely used technical indicator that smooths out price data by calculating the average price over a specific number of periods. The two main types are Simple Moving Average (SMA) and Exponential Moving Average (EMA), which gives more weight to recent prices. Common periods are 20 (short-term), 50 (medium-term), and 200 (long-term) days. The crossover of shorter and longer MAs signals trend changes.`,
    category: 'Technical Analysis',
    example: 'When the 50-day MA crosses above the 200-day MA (Golden Cross), it signals a bullish trend.',
    tags: ['ma', 'sma', 'ema', 'trend', 'indicator'],
    icon: '〰️',
    relatedTerms: ['technical-analysis', 'rsi', 'macd'],
  },
  {
    id: 'rsi',
    term: 'Relative Strength Index (RSI)',
    shortDefinition: 'Momentum oscillator measuring speed and magnitude of price changes.',
    detailedDefinition: `The Relative Strength Index (RSI) is a momentum oscillator that measures the speed and magnitude of recent price changes to evaluate overbought or oversold conditions. RSI ranges from 0 to 100. Traditionally, RSI above 70 indicates overbought conditions (potential sell signal), and RSI below 30 indicates oversold conditions (potential buy signal). The standard period is 14 days.`,
    category: 'Technical Analysis',
    example: 'A stock\'s RSI reaches 85 — traders watch for a potential pullback as the stock is overbought.',
    tags: ['overbought', 'oversold', 'momentum', 'oscillator'],
    icon: '📊',
    relatedTerms: ['technical-analysis', 'moving-average', 'macd'],
  },
  {
    id: 'macd',
    term: 'MACD',
    shortDefinition: 'Trend-following momentum indicator showing trend strength and direction.',
    detailedDefinition: `MACD (Moving Average Convergence Divergence) is a trend-following momentum indicator that shows the relationship between two moving averages of a security's price. It consists of three components: the MACD line (12-day EMA minus 26-day EMA), the signal line (9-day EMA of MACD), and the histogram (difference between MACD and signal line). When MACD crosses above the signal line, it is bullish; below is bearish.`,
    category: 'Technical Analysis',
    example: 'MACD line crosses above the signal line — a common bullish signal used by traders worldwide.',
    tags: ['indicator', 'momentum', 'trend', 'crossover'],
    icon: '📈',
    relatedTerms: ['technical-analysis', 'moving-average', 'rsi'],
  },
  {
    id: 'candlestick',
    term: 'Candlestick Pattern',
    shortDefinition: 'Chart pattern showing open, high, low, close prices for a period.',
    detailedDefinition: `Candlestick patterns are a style of financial chart used to describe price movements. Each candlestick shows four prices: open, high, low, and close for a specific time period. The body (rectangle) shows the open-close range, and the wicks (lines) show the high-low range. Common patterns include Doji, Hammer, Engulfing, Morning Star, and Evening Star. Candlestick patterns help traders predict potential price movements.`,
    category: 'Technical Analysis',
    example: 'A Hammer candlestick pattern after a downtrend suggests a potential bullish reversal.',
    tags: ['chart', 'pattern', 'reversal', 'japanese'],
    icon: '🕯️',
    relatedTerms: ['technical-analysis', 'support-resistance'],
  },
  {
    id: 'volume',
    term: 'Volume',
    shortDefinition: 'Number of shares traded in a given period.',
    detailedDefinition: `Volume measures the number of shares or contracts traded during a specific period. High volume confirms the strength of a price move — rising prices on high volume are more reliable. Low volume suggests weak conviction. Volume analysis is a crucial component of technical analysis, often used alongside price patterns to confirm trends and identify potential reversals.`,
    category: 'Technical Analysis',
    example: 'Nifty rises 200 points with 2x average volume — this confirms strong bullish conviction.',
    tags: ['trading', 'activity', 'confirmation', 'liquidity'],
    icon: '📊',
    relatedTerms: ['technical-analysis', 'breakout'],
  },
  {
    id: 'breakout',
    term: 'Breakout',
    shortDefinition: 'Price moving above resistance or below support with increased volume.',
    detailedDefinition: `A breakout occurs when the price of an asset moves above a resistance level or below a support level, often accompanied by increased volume. Breakouts signal the start of a new trend and are key trading opportunities. False breakouts (price breaking through a level but quickly reversing) are common, so traders often wait for a confirmed close above/below the level before acting.`,
    category: 'Technical Analysis',
    example: 'Bank Nifty breaks above 48,000 resistance level with 3x average volume — a bullish breakout.',
    tags: ['breakout', 'trend', 'confirmation', 'entry'],
    icon: '💥',
    relatedTerms: ['technical-analysis', 'support-resistance', 'volume'],
  },

  // ═══════════════════ FUNDAMENTAL ANALYSIS ═══════════════════
  {
    id: 'fundamental-analysis',
    term: 'Fundamental Analysis',
    shortDefinition: 'Evaluating a company\'s financial health to determine its intrinsic value.',
    detailedDefinition: `Fundamental analysis is a method of evaluating a company's intrinsic value by examining its financial statements, management, competitive advantages, industry position, and economic environment. Analysts study revenue, profits, debt, cash flow, P/E ratio, ROE, and other financial metrics. The goal is to determine whether a stock is undervalued or overvalued compared to its current market price.`,
    category: 'Fundamental Analysis',
    example: 'Warren Buffett analyzes a company\'s balance sheet, management quality, and competitive moat before investing.',
    tags: ['value', 'financials', 'analysis', 'intrinsic-value'],
    icon: '🔍',
    relatedTerms: ['pe-ratio', 'eps', 'roe', 'ebitda', 'intrinsic-value'],
  },
  {
    id: 'pe-ratio',
    term: 'Price-to-Earnings (P/E) Ratio',
    shortDefinition: 'Ratio of stock price to earnings per share, indicating valuation.',
    detailedDefinition: `The Price-to-Earnings (P/E) ratio measures a company's current share price relative to its earnings per share (EPS). It tells you how much investors are willing to pay for each rupee of earnings. A high P/E may indicate overvaluation or high growth expectations; a low P/E may indicate undervaluation or low growth prospects. Compare P/E ratios within the same industry for meaningful analysis.`,
    category: 'Fundamental Analysis',
    example: 'If a stock trades at ₹500 and its EPS is ₹25, the P/E ratio is 20 (500/25 = 20).',
    tags: ['valuation', 'multiple', 'cheap', 'expensive'],
    icon: '📊',
    relatedTerms: ['eps', 'fundamental-analysis', 'intrinsic-value'],
  },
  {
    id: 'eps',
    term: 'Earnings Per Share (EPS)',
    shortDefinition: 'Company\'s profit divided by its outstanding shares.',
    detailedDefinition: `Earnings Per Share (EPS) is calculated by dividing a company's net profit by its total number of outstanding shares. EPS is a key indicator of a company's profitability. Higher EPS means the company is generating more profit per share. Investors track EPS growth over time — consistently rising EPS is a sign of a healthy, growing company.`,
    category: 'Fundamental Analysis',
    example: 'If a company earns ₹100 crore profit and has 10 crore shares, its EPS is ₹10.',
    tags: ['profit', 'earnings', 'per-share', 'profitability'],
    icon: '💵',
    relatedTerms: ['pe-ratio', 'fundamental-analysis', 'roe'],
  },
  {
    id: 'roe',
    term: 'Return on Equity (ROE)',
    shortDefinition: 'Profit generated from shareholders\' equity.',
    detailedDefinition: `Return on Equity (ROE) measures a company's profitability by showing how much profit it generates with the money shareholders have invested. ROE is calculated as Net Income ÷ Shareholders' Equity. A consistently high ROE (above 15-20%) indicates efficient management and strong competitive advantages. However, high debt can artificially inflate ROE, so it should be analyzed alongside debt levels.`,
    category: 'Fundamental Analysis',
    example: 'A company with ₹100 crore net profit and ₹500 crore equity has an ROE of 20%.',
    tags: ['profitability', 'efficiency', 'shareholder-returns'],
    icon: '📈',
    relatedTerms: ['fundamental-analysis', 'eps', 'debt-equity'],
  },
  {
    id: 'ebitda',
    term: 'EBITDA',
    shortDefinition: 'Earnings before interest, taxes, depreciation, and amortization.',
    detailedDefinition: `EBITDA (Earnings Before Interest, Taxes, Depreciation, and Amortization) measures a company's operating performance by excluding non-operating expenses. It shows how much cash profit a company generates from its core operations. EBITDA is useful for comparing companies with different capital structures and tax situations. However, it does not account for capital expenditure needs.`,
    category: 'Fundamental Analysis',
    example: 'A company with ₹500 crore revenue and ₹300 crore operating expenses has an EBITDA of ₹200 crore.',
    tags: ['operating-profit', 'cash-profit', 'earnings'],
    icon: '📋',
    relatedTerms: ['fundamental-analysis', 'pe-ratio'],
  },
  {
    id: 'intrinsic-value',
    term: 'Intrinsic Value',
    shortDefinition: 'The true worth of a company based on fundamental analysis.',
    detailedDefinition: `Intrinsic value is the perceived or calculated true value of a company, independent of its current market price. It is determined through fundamental analysis using methods like Discounted Cash Flow (DCF) analysis, comparable company analysis, and asset-based valuation. When the market price is below intrinsic value, the stock is considered undervalued and potentially a good buy. This concept was popularized by Benjamin Graham and Warren Buffett.`,
    category: 'Fundamental Analysis',
    example: 'After DCF analysis, a trader calculates a stock\'s intrinsic value at ₹850 while it trades at ₹650 — a potential buying opportunity.',
    tags: ['valuation', 'true-value', 'margin-of-safety', 'dcf'],
    icon: '🎯',
    relatedTerms: ['fundamental-analysis', 'pe-ratio', 'margin-of-safety'],
  },
  {
    id: 'margin-of-safety',
    term: 'Margin of Safety',
    shortDefinition: 'Difference between intrinsic value and market price.',
    detailedDefinition: `Margin of Safety is the difference between a company's intrinsic value and its current market price. Popularized by Benjamin Graham, it represents a buffer against errors in analysis or unforeseen events. The larger the margin of safety, the lower the risk. Value investors typically look for stocks trading at least 20-30% below their intrinsic value to build in a safety cushion.`,
    category: 'Fundamental Analysis',
    example: 'If a stock\'s intrinsic value is ₹100 and it trades at ₹70, the margin of safety is 30%.',
    tags: ['safety', 'buffer', 'value-investing', 'graham'],
    icon: '🛡️',
    relatedTerms: ['intrinsic-value', 'fundamental-analysis'],
  },

  // ═══════════════════ TAX & REGULATIONS ═══════════════════
  {
    id: 'stcg',
    term: 'Short-Term Capital Gains (STCG)',
    shortDefinition: 'Profit from selling an asset held for 12 months or less.',
    detailedDefinition: `Short-Term Capital Gains (STCG) arise when you sell an asset within 12 months of purchase. For equity shares and equity mutual funds sold within 12 months, STCG is taxed at 15%. For other assets like debt funds or real estate, STCG is added to your income and taxed as per your income tax slab. STCG is one of the most important tax concepts for active traders.`,
    category: 'Tax',
    example: 'Ravi bought shares at ₹10,000 and sold them after 6 months at ₹12,000 — the ₹2,000 profit is STCG taxed at 15%.',
    tags: ['short-term', 'tax', 'capital-gains', '15%'],
    icon: '📉',
    relatedTerms: ['ltcg', 'capital-gains', 'tax-harvesting'],
  },
  {
    id: 'ltcg',
    term: 'Long-Term Capital Gains (LTCG)',
    shortDefinition: 'Profit from selling an asset held for more than 12 months.',
    detailedDefinition: `Long-Term Capital Gains (LTCG) arise when you sell an asset after holding it for more than 12 months. For equity shares and equity mutual funds, LTCG exceeding ₹1 lakh in a financial year is taxed at 10% without indexation benefit. Gains up to ₹1 lakh are tax-free. For debt funds held for more than 36 months, LTCG is taxed at 20% with indexation. Understanding LTCG is crucial for long-term investors.`,
    category: 'Tax',
    example: 'An investor made ₹2.5 lakh profit selling shares held for 2 years — ₹1 lakh is tax-free, remaining ₹1.5 lakh taxed at 10%.',
    tags: ['long-term', 'tax', 'capital-gains', '10%', '1-lakh'],
    icon: '📈',
    relatedTerms: ['stcg', 'capital-gains', 'tax-harvesting'],
  },
  {
    id: 'capital-gains',
    term: 'Capital Gains',
    shortDefinition: 'Profit from selling a capital asset.',
    detailedDefinition: `Capital gains refer to the profit earned when you sell a capital asset (stocks, mutual funds, real estate, gold) at a price higher than your purchase price. Capital gains are classified as Short-Term or Long-Term based on the holding period. Gains are taxable in the year of sale. Losses can be set off against gains and carried forward.`,
    category: 'Tax',
    example: 'Buying a house for ₹50 lakh and selling it for ₹80 lakh after 5 years generates ₹30 lakh in capital gains.',
    tags: ['profit', 'tax', 'sale', 'asset'],
    icon: '💰',
    relatedTerms: ['stcg', 'ltcg', 'tax-harvesting'],
  },
  {
    id: 'tax-harvesting',
    term: 'Tax Harvesting',
    shortDefinition: 'Selling assets at a loss to offset capital gains and reduce taxes.',
    detailedDefinition: `Tax harvesting is a strategy where investors sell underperforming investments at a loss to offset capital gains from winning investments. By realizing losses, you reduce your net taxable capital gains. In India, short-term capital losses can offset both STCG and LTCG. Long-term capital losses can only offset LTCG. Unused losses can be carried forward for 8 assessment years.`,
    category: 'Tax',
    example: 'An investor sells a losing stock at ₹50,000 loss to offset ₹50,000 in gains from another stock — net tax = zero.',
    tags: ['loss', 'offset', 'tax-saving', 'strategy'],
    icon: '🌾',
    relatedTerms: ['stcg', 'ltcg', 'capital-gains'],
  },
  {
    id: 'tds',
    term: 'Tax Deducted at Source (TDS)',
    shortDefinition: 'Tax deducted by the payer before making a payment.',
    detailedDefinition: `TDS (Tax Deducted at Source) is a tax collection mechanism where the person making a payment deducts tax before paying the recipient. Common TDS applies to interest on fixed deposits (10% if interest exceeds ₹40,000), dividends (10% if above ₹5,000), and salaries. The deducted tax is deposited with the government and credited to the recipient's tax account.`,
    category: 'Tax',
    example: 'Your bank deducts 10% TDS on FD interest before crediting it to your account.',
    tags: ['tax', 'deduction', 'fd', 'interest'],
    icon: '📋',
    relatedTerms: ['capital-gains', 'stt'],
  },
  {
    id: 'stt',
    term: 'Securities Transaction Tax (STT)',
    shortDefinition: 'Tax paid on every stock market transaction.',
    detailedDefinition: `STT (Securities Transaction Tax) is a tax levied on every purchase and sale of securities on Indian stock exchanges. For delivery-based equity trading, STT is 0.1% on both buy and sell sides. For intraday trading, it is 0.025% on the sell side only. STT is automatically deducted by your broker and cannot be avoided. It is an essential cost of trading that affects net profitability.`,
    category: 'Tax',
    example: 'If you buy ₹1,00,000 worth of shares for delivery, you pay ₹100 as STT (0.1%).',
    tags: ['transaction', 'tax', 'trading', 'brokerage'],
    icon: '🏛️',
    relatedTerms: ['capital-gains', 'tds'],
  },
  {
    id: 'section-80c',
    term: 'Section 80C',
    shortDefinition: 'Tax deduction on investments up to ₹1.5 lakh per year.',
    detailedDefinition: `Section 80C of the Income Tax Act allows individual taxpayers to claim deductions of up to ₹1.5 lakh per financial year on specified investments and expenses. Eligible instruments include PPF, EPF, ELSS mutual funds, life insurance premiums, NSC, tax-saving FDs, and home loan principal repayment. Section 80C is the most popular tax-saving provision for Indian investors.`,
    category: 'Tax',
    example: 'Investing ₹1.5 lakh in ELSS funds qualifies for full deduction under Section 80C, saving up to ₹46,800 in tax.',
    tags: ['deduction', 'tax-saving', '80c', 'ppf', 'elss'],
    icon: '✅',
    relatedTerms: ['elss', 'ppf'],
  },
  {
    id: 'elss',
    term: 'Equity Linked Savings Scheme (ELSS)',
    shortDefinition: 'Tax-saving mutual fund with 3-year lock-in.',
    detailedDefinition: `ELSS (Equity Linked Savings Scheme) is a type of diversified equity mutual fund that qualifies for tax deduction under Section 80C. It has the shortest lock-in period (3 years) among all 80C investment options. ELSS funds invest primarily in equity markets, offering potential for higher returns compared to other tax-saving options like PPF or NSC. Returns are subject to capital gains tax.`,
    category: 'Tax',
    example: 'Investing ₹1.5 lakh in an ELSS fund saves up to ₹46,800 in taxes under the old tax regime.',
    tags: ['tax-saving', '80c', 'mutual-fund', 'equity', 'lock-in'],
    icon: '🌟',
    relatedTerms: ['section-80c', 'mutual-fund', 'ppf'],
  },
  {
    id: 'ppf',
    term: 'Public Provident Fund (PPF)',
    shortDefinition: 'Government-backed long-term savings scheme with tax benefits.',
    detailedDefinition: `PPF (Public Provident Fund) is a government-backed long-term savings scheme with a 15-year maturity period. Contributions up to ₹1.5 lakh per year qualify for tax deduction under Section 80C. The interest rate (currently ~7.1%) is set quarterly by the government. The entire corpus — principal, interest, and maturity amount — is tax-free. PPF is considered one of the safest investment options in India.`,
    category: 'Tax',
    example: 'Investing ₹1.5 lakh annually in PPF for 15 years grows to approximately ₹40+ lakh tax-free.',
    tags: ['savings', 'tax-free', 'safe', 'government', 'retirement'],
    icon: '🏦',
    relatedTerms: ['section-80c', 'elss', 'epf'],
  },
  {
    id: 'epf',
    term: 'Employee Provident Fund (EPF)',
    shortDefinition: 'Mandatory retirement savings fund for salaried employees.',
    detailedDefinition: `EPF (Employee Provident Fund) is a mandatory retirement savings scheme for salaried employees in India. Both employee and employer contribute 12% of the employee's basic salary to the EPF account. The interest rate (currently ~8.15%) is tax-free. The entire EPF corpus is tax-free if held for more than 5 years. EPF contributions also qualify for deduction under Section 80C.`,
    category: 'Tax',
    example: 'An employee earning ₹50,000/month (basic pay) contributes ₹6,000 (12%) to EPF monthly, matched by the employer.',
    tags: ['retirement', 'pf', 'savings', 'employer', '80c'],
    icon: '🏛️',
    relatedTerms: ['section-80c', 'ppf', 'nps'],
  },
  {
    id: 'nps',
    term: 'National Pension System (NPS)',
    shortDefinition: 'Government-sponsored pension cum investment scheme.',
    detailedDefinition: `NPS (National Pension System) is a voluntary, government-sponsored retirement savings scheme. It offers tax benefits under Section 80CCD(1B) — an additional deduction of up to ₹50,000 over the ₹1.5 lakh 80C limit. Upon maturity (60 years), 60% of the corpus can be withdrawn tax-free, while 40% must be used to purchase an annuity (taxable). NPS invests in equity, corporate bonds, and government securities.`,
    category: 'Tax',
    example: 'A 30-year-old investing ₹50,000/year in NPS gets an extra tax deduction of ₹50,000 under Section 80CCD(1B).',
    tags: ['pension', 'retirement', 'tax-saving', '80ccd'],
    icon: '👴',
    relatedTerms: ['epf', 'ppf', 'section-80c'],
  },

  // ═══════════════════ ECONOMY ═══════════════════
  {
    id: 'inflation',
    term: 'Inflation',
    shortDefinition: 'Rate at which the general price level of goods and services rises.',
    detailedDefinition: `Inflation measures how much more expensive goods and services have become over a period, usually a year. In India, inflation is measured by the Consumer Price Index (CPI) and Wholesale Price Index (WPI). Moderate inflation (2-6%) is normal in a growing economy. High inflation erodes purchasing power and can lead to higher interest rates. Inflation is a key factor that central banks (RBI) monitor to set monetary policy.`,
    category: 'Economy',
    example: 'If inflation is 6%, goods that cost ₹100 last year now cost ₹106 — your money buys less than before.',
    tags: ['cpi', 'wpi', 'prices', 'rbi', 'monetary-policy'],
    icon: '📈',
    relatedTerms: ['rbi', 'interest-rate', 'gdp'],
  },
  {
    id: 'gdp',
    term: 'Gross Domestic Product (GDP)',
    shortDefinition: 'Total value of all goods and services produced in a country.',
    detailedDefinition: `GDP (Gross Domestic Product) is the total monetary value of all finished goods and services produced within a country's borders in a specific time period. It is the most comprehensive measure of a nation's economic activity. India's GDP growth rate (currently ~6-7%) is one of the highest among major economies. GDP growth drives corporate earnings, stock market returns, and employment generation.`,
    category: 'Economy',
    example: 'India\'s GDP grew by 7.2% in FY24, making it the fastest-growing major economy in the world.',
    tags: ['economy', 'growth', 'output', 'national-income'],
    icon: '🌍',
    relatedTerms: ['inflation', 'rbi', 'recession'],
  },
  {
    id: 'rbi',
    term: 'Reserve Bank of India (RBI)',
    shortDefinition: 'India\'s central bank that regulates monetary policy and banking.',
    detailedDefinition: `The Reserve Bank of India (RBI) is India's central banking institution that controls the monetary policy, regulates banks, manages foreign exchange, and issues currency. The RBI uses tools like the repo rate, reverse repo rate, and Cash Reserve Ratio (CRR) to control inflation and stimulate growth. RBI decisions have a significant impact on stock markets, interest rates, and the overall economy.`,
    category: 'Economy',
    example: 'When RBI raises the repo rate, home loans become more expensive, and stock markets often react negatively.',
    tags: ['central-bank', 'monetary-policy', 'interest-rates', 'banking'],
    icon: '🏛️',
    relatedTerms: ['inflation', 'interest-rate', 'gdp', 'repo-rate'],
  },
  {
    id: 'repo-rate',
    term: 'Repo Rate',
    shortDefinition: 'Rate at which RBI lends money to commercial banks.',
    detailedDefinition: `The repo rate is the interest rate at which the Reserve Bank of India (RBI) lends money to commercial banks for short-term needs. When the repo rate is high, banks borrow less and lend at higher rates, reducing money supply and curbing inflation. A lower repo rate makes loans cheaper, encourages spending and investment, and boosts economic growth. Repo rate changes directly affect home loan EMIs, business loans, and stock markets.`,
    category: 'Economy',
    example: 'RBI cuts repo rate by 25 bps — home loan EMIs decrease, and the stock market rallies on the news.',
    tags: ['rbi', 'interest-rate', 'monetary-policy', 'lending'],
    icon: '💹',
    relatedTerms: ['rbi', 'inflation', 'interest-rate'],
  },
  {
    id: 'interest-rate',
    term: 'Interest Rate',
    shortDefinition: 'Cost of borrowing money, expressed as a percentage.',
    detailedDefinition: `An interest rate is the percentage charged by lenders for borrowing money. In investing, interest rates affect everything from bond prices and stock valuations to home loan EMIs and FD returns. Rising interest rates generally hurt stock markets (higher borrowing costs reduce corporate profits) and benefit fixed-income investors. Falling rates benefit stocks and borrowers but reduce FD returns.`,
    category: 'Economy',
    example: 'A 1% increase in interest rates can reduce a company\'s profit by 5-10% due to higher borrowing costs.',
    tags: ['rbi', 'borrowing', 'cost', 'monetary-policy'],
    icon: '📊',
    relatedTerms: ['rbi', 'repo-rate', 'inflation', 'bond'],
  },
  {
    id: 'recession',
    term: 'Recession',
    shortDefinition: 'A significant decline in economic activity across the economy.',
    detailedDefinition: `A recession is a significant, widespread, and prolonged downturn in economic activity. It is commonly defined as two consecutive quarters of negative GDP growth. During a recession, unemployment rises, consumer spending falls, corporate profits decline, and stock markets typically fall. Recessions are a natural part of the economic cycle and can be caused by financial crises, high inflation, or external shocks.`,
    category: 'Economy',
    example: 'During the 2008 recession, the Indian stock market fell over 50% from its peak, and GDP growth slowed to 3.9%.',
    tags: ['downturn', 'contraction', 'gdp', 'crisis'],
    icon: '📉',
    relatedTerms: ['gdp', 'inflation', 'bear-market'],
  },
  {
    id: 'bear-market',
    term: 'Bear Market',
    shortDefinition: 'A market condition where prices fall 20% or more from recent highs.',
    detailedDefinition: `A bear market is a prolonged period of declining stock prices, typically defined as a decline of 20% or more from recent highs. Bear markets are characterized by widespread pessimism, investor fear, and negative sentiment. They can last months or years. Despite the negative connotations, bear markets often present excellent buying opportunities for long-term investors.`,
    category: 'Economy',
    example: 'The COVID-19 bear market in 2020 saw the Nifty fall 38% in just 23 days — followed by a sharp recovery.',
    tags: ['decline', 'crash', 'pessimism', 'downturn'],
    icon: '🐻',
    relatedTerms: ['bull-market', 'recession', 'correction'],
  },
  {
    id: 'bull-market',
    term: 'Bull Market',
    shortDefinition: 'A market condition where prices are rising or expected to rise.',
    detailedDefinition: `A bull market is a period of rising stock prices, typically defined as a 20% increase from recent lows. Bull markets are characterized by optimism, investor confidence, and strong economic fundamentals. They can last for years — the longest bull market in Indian history lasted from 2012 to 2025 with brief interruptions. Bull markets are driven by economic growth, corporate earnings, and investor sentiment.`,
    category: 'Economy',
    example: 'The Nifty rose from 8,000 in 2016 to over 25,000 in 2025 — one of the longest bull markets in Indian history.',
    tags: ['rise', 'rally', 'optimism', 'growth'],
    icon: '🐂',
    relatedTerms: ['bear-market', 'gdp', 'correction'],
  },
  {
    id: 'correction',
    term: 'Correction',
    shortDefinition: 'A short-term price decline of 10% or more from a peak.',
    detailedDefinition: `A correction is a short-term decline in stock prices of 10% or more from a recent peak, typically lasting from a few weeks to a few months. Corrections are normal and healthy market phenomena that occur during both bull and bear markets. They often present buying opportunities for investors who missed earlier rallies. On average, the market experiences a correction once every 1-2 years.`,
    category: 'Economy',
    example: 'The Nifty fell 12% in June 2025 — a normal correction in an otherwise strong bull market.',
    tags: ['decline', 'pullback', 'dip', 'buying-opportunity'],
    icon: '📉',
    relatedTerms: ['bear-market', 'bull-market', 'crash'],
  },

  // ═══════════════════ IPO ═══════════════════
  {
    id: 'ipo',
    term: 'Initial Public Offering (IPO)',
    shortDefinition: 'When a company first sells shares to the public.',
    detailedDefinition: `An IPO (Initial Public Offering) is the process by which a private company becomes publicly traded by offering its shares to the general public for the first time. Companies use IPOs to raise capital for expansion, provide liquidity to existing shareholders, and increase brand visibility. In India, IPOs are regulated by SEBI and require a Detailed Red Herring Prospectus (DRHP) explaining the company's business and financials.`,
    category: 'IPO',
    example: 'Zomato\'s ₹9,375 crore IPO in 2021 was oversubscribed 38 times on the final day.',
    tags: ['listing', 'public-offer', 'drhp', 'sebi'],
    icon: '🚀',
    relatedTerms: ['gmp', 'listing-gain', 'fpo', 'drhp'],
  },
  {
    id: 'gmp',
    term: 'Grey Market Premium (GMP)',
    shortDefinition: 'Unofficial premium at which IPO shares trade before listing.',
    detailedDefinition: `GMP (Grey Market Premium) is the unofficial price at which IPO shares are traded in the unregulated \"grey market\" before their official stock exchange listing. It reflects investor demand and expectations for the IPO. A high GMP suggests strong listing gains, while a low or negative GMP indicates weak demand. However, GMP is not an official indicator and can be manipulated.`,
    category: 'IPO',
    example: 'If an IPO is priced at ₹200 and trades at ₹280 in the grey market, the GMP is ₹80 (40% premium).',
    tags: ['unlisted', 'pre-listing', 'demand', 'premium'],
    icon: '💼',
    relatedTerms: ['ipo', 'listing-gain'],
  },
  {
    id: 'listing-gain',
    term: 'Listing Gain',
    shortDefinition: 'Profit made when IPO shares lists at a higher price than the issue price.',
    detailedDefinition: `Listing gain is the profit an investor makes if an IPO share lists (starts trading) at a price higher than the issue price on the stock exchange. For example, if an IPO is issued at ₹500 and lists at ₹650, the listing gain is 30%. IPOs with high demand often list at a significant premium. Many investors apply for IPOs solely for listing gains and sell on the listing day.`,
    category: 'IPO',
    example: 'Tata Technologies IPO was issued at ₹500 and listed at ₹1,200 — a 140% listing gain!',
    tags: ['profit', 'listing', 'premium', 'ipo'],
    icon: '📈',
    relatedTerms: ['ipo', 'gmp'],
  },
  {
    id: 'fpo',
    term: 'Follow-on Public Offer (FPO)',
    shortDefinition: 'Additional shares sold by an already-public company.',
    detailedDefinition: `A Follow-on Public Offer (FPO) is when an already publicly listed company issues additional shares to raise more capital from investors. Unlike an IPO (first-time offering), an FPO involves a company that is already listed on the stock exchange. FPOs can be dilutive (new shares issued, reducing existing holders' percentage) or non-dilutive (existing shareholders selling their shares).`,
    category: 'IPO',
    example: 'Vodafone Idea launched a ₹18,000 crore FPO in 2024 to raise funds for network expansion.',
    tags: ['public-offer', 'capital-raise', 'dilution'],
    icon: '📋',
    relatedTerms: ['ipo', 'rights-issue'],
  },
  {
    id: 'drhp',
    term: 'Draft Red Herring Prospectus (DRHP)',
    shortDefinition: 'Detailed document filed by a company before an IPO.',
    detailedDefinition: `A DRHP (Draft Red Herring Prospectus) is a detailed document filed by a company with SEBI before launching an IPO. It contains comprehensive information about the company — business model, financial statements, promoters, risks, competitive strengths, and the offer details. Investors should read the DRHP carefully before applying for an IPO to make an informed decision.`,
    category: 'IPO',
    example: 'Investors read the DRHP of OYO before its IPO to understand its business model and financial health.',
    tags: ['document', 'sebi', 'prospectus', 'disclosure'],
    icon: '📄',
    relatedTerms: ['ipo', 'sebi'],
  },

  // ═══════════════════ BONDS & DEBT ═══════════════════
  {
    id: 'bond',
    term: 'Bond',
    shortDefinition: 'A loan made by an investor to a borrower (company or government).',
    detailedDefinition: `A bond is a fixed-income instrument that represents a loan made by an investor to a borrower (typically corporate or governmental). The issuer promises to pay a fixed interest rate (coupon) periodically and return the principal amount at maturity. Bonds are considered safer than stocks but offer lower returns. Government bonds (G-Secs) are the safest, while corporate bonds offer higher yields with higher risk.`,
    category: 'Bonds & Debt',
    example: 'Buying a 10-year government bond with 7% coupon gives you ₹7,000 annual interest on ₹1,00,000 invested.',
    tags: ['fixed-income', 'debt', 'coupon', 'yield', 'g-sec'],
    icon: '📜',
    relatedTerms: ['yield', 'credit-rating', 'interest-rate'],
  },
  {
    id: 'yield',
    term: 'Yield',
    shortDefinition: 'The return generated by an investment, expressed as a percentage.',
    detailedDefinition: `Yield is the income return on an investment, expressed as a percentage of its current price. For bonds, yield is the annual interest divided by the current market price. For stocks, dividend yield is annual dividends divided by stock price. Bond yields and prices move inversely — when prices fall, yields rise and vice versa. Yield is a key metric for income-focused investors.`,
    category: 'Bonds & Debt',
    example: 'A ₹1,000 bond paying ₹80 annual interest has a yield of 8%. If the bond price falls to ₹800, yield rises to 10%.',
    tags: ['return', 'income', 'interest', 'dividend'],
    icon: '💹',
    relatedTerms: ['bond', 'dividend', 'interest-rate'],
  },
  {
    id: 'credit-rating',
    term: 'Credit Rating',
    shortDefinition: 'Assessment of a borrower\'s ability to repay debt.',
    detailedDefinition: `A credit rating evaluates a borrower's (company or government) ability to repay its debt obligations. Ratings are assigned by agencies like CRISIL, ICRA, and CARE in India. The highest rating is AAA (safest), followed by AA, A, BBB, BB, B, C, and D (default). Higher-rated bonds offer lower yields but carry less risk. Credit rating downgrades can cause bond prices to fall sharply.`,
    category: 'Bonds & Debt',
    example: 'Reliance Industries has a AAA credit rating, meaning it has the highest capacity to repay its debts.',
    tags: ['crisil', 'icra', 'default', 'risk', 'aaa'],
    icon: '⭐',
    relatedTerms: ['bond', 'yield'],
  },

  // ═══════════════════ GOLD & COMMODITIES ═══════════════════
  {
    id: 'commodity',
    term: 'Commodity',
    shortDefinition: 'Raw materials or primary agricultural products that can be traded.',
    detailedDefinition: `A commodity is a basic good used in commerce that is interchangeable with other goods of the same type. Commodities include metals (gold, silver, copper), energy (crude oil, natural gas), and agricultural products (wheat, coffee, cotton). Commodities are traded on exchanges like MCX in India. Investing in commodities provides portfolio diversification and acts as a hedge against inflation.`,
    category: 'Gold & Commodities',
    example: 'Gold prices rose 15% in 2025 as investors sought a safe-haven asset during global uncertainty.',
    tags: ['gold', 'silver', 'crude', 'mcx', 'hedge'],
    icon: '🛢️',
    relatedTerms: ['gold', 'inflation', 'diversification'],
  },
  {
    id: 'gold',
    term: 'Gold',
    shortDefinition: 'A precious metal used as an investment and inflation hedge.',
    detailedDefinition: `Gold is a precious metal that has been used as a store of value for thousands of years. It is considered a safe-haven asset that retains its value during economic uncertainty, inflation, and market volatility. In India, gold is culturally significant and can be invested in physically (jewelry, coins, bars), through Sovereign Gold Bonds (SGBs), Gold ETFs, or digital gold. SGBs offer additional interest income and tax-free maturity.`,
    category: 'Gold & Commodities',
    example: 'Investing in Sovereign Gold Bonds gives 2.5% annual interest plus capital appreciation — tax-free at maturity.',
    tags: ['safe-haven', 'sgb', 'hedge', 'precious-metal'],
    icon: '🥇',
    relatedTerms: ['commodity', 'inflation', 'etf'],
  },
  {
    id: 'sgb',
    term: 'Sovereign Gold Bond (SGB)',
    shortDefinition: 'Government-backed gold investment with annual interest.',
    detailedDefinition: `Sovereign Gold Bonds (SGBs) are government securities denominated in grams of gold. They are an alternative to holding physical gold. SGBs pay a fixed interest rate (currently 2.5% per annum) semi-annually and are issued by the RBI. The bond price tracks gold prices. If held to maturity (8 years), capital gains are completely tax-free. SGBs are one of the most tax-efficient ways to invest in gold.`,
    category: 'Gold & Commodities',
    example: 'Buying 10 grams of SGB at ₹6,000/gram = ₹60,000 investment, earning ₹1,500 annual interest tax-free.',
    tags: ['gold', 'tax-free', 'rbi', 'bond', 'safe'],
    icon: '💛',
    relatedTerms: ['gold', 'bond', 'commodity'],
  },

  // ═══════════════════ REAL ESTATE ═══════════════════
  {
    id: 'real-estate',
    term: 'Real Estate',
    shortDefinition: 'Land and buildings used as an investment asset.',
    detailedDefinition: `Real estate refers to land, buildings, and natural resources. As an investment, it includes residential property, commercial property, and REITs (Real Estate Investment Trusts). In India, real estate has historically been a popular investment for wealth creation. Returns come from rental income and capital appreciation. Real estate offers diversification but has lower liquidity than stocks or bonds.`,
    category: 'Real Estate',
    example: 'Buying an apartment for ₹50 lakh and renting it for ₹25,000/month gives a 6% rental yield.',
    tags: ['property', 'land', 'building', 'reit', 'rental'],
    icon: '🏠',
    relatedTerms: ['reit'],
  },
  {
    id: 'reit',
    term: 'Real Estate Investment Trust (REIT)',
    shortDefinition: 'A company that owns and operates income-generating real estate.',
    detailedDefinition: `A REIT (Real Estate Investment Trust) is a company that owns, operates, or finances income-producing real estate. REITs allow investors to invest in large-scale, income-generating real estate without having to buy properties directly. In India, listed REITs like Embassy Office Parks and Mindspace Business Parks offer regular dividend income. REITs must distribute 90% of their income to unitholders.`,
    category: 'Real Estate',
    example: 'Buying units of Embassy Office Parks REIT gives you exposure to commercial office properties and quarterly dividends.',
    tags: ['property', 'dividend', 'income', 'commercial'],
    icon: '🏢',
    relatedTerms: ['real-estate', 'dividend'],
  },

  // ═══════════════════ TRADING ═══════════════════
  {
    id: 'intraday',
    term: 'Intraday Trading',
    shortDefinition: 'Buying and selling stocks within the same trading day.',
    detailedDefinition: `Intraday trading involves buying and selling stocks or other financial instruments within the same trading day. All positions must be closed (squared off) by the market close at 3:30 PM. Intraday traders profit from small price movements during the day and use leverage provided by brokers. It is high-risk because prices can move sharply, and losses can exceed the invested capital.`,
    category: 'Trading',
    example: 'A day trader buys 100 shares of RIL at ₹2,500 and sells at ₹2,545 within hours — profit of ₹4,500.',
    tags: ['day-trading', 'short-term', 'high-risk', 'leverage'],
    icon: '⚡',
    relatedTerms: ['delivery-trading', 'margin-trading', 'speculation'],
  },
  {
    id: 'delivery-trading',
    term: 'Delivery Trading',
    shortDefinition: 'Buying stocks that are credited to your Demat account (long-term).',
    detailedDefinition: `Delivery trading (also called CNC — Cash N Carry) is when you buy stocks by paying the full amount, and the shares are credited to your Demat account. You can hold them indefinitely. Delivery trading is suitable for long-term investors. It attracts lower STT (0.1% on buy and sell) compared to intraday. Most long-term wealth creation happens through delivery-based investing.`,
    category: 'Trading',
    example: 'Buying 50 shares of TCS at ₹4,000 by paying the full ₹2,00,000 — shares are credited to your Demat account.',
    tags: ['cnc', 'long-term', 'holding', 'demat'],
    icon: '📦',
    relatedTerms: ['intraday', 'demat', 'stt'],
  },
  {
    id: 'margin-trading',
    term: 'Margin Trading',
    shortDefinition: 'Borrowing money from a broker to trade larger positions.',
    detailedDefinition: `Margin trading allows you to buy securities by borrowing money from your broker. You put up a percentage (margin) of the trade value, and the broker lends the rest. Margin amplifies both gains and losses. SEBI regulates margin requirements through the Peak Margin framework. While margin can boost returns, it also increases risk — losses can exceed your initial investment.`,
    category: 'Trading',
    example: 'With ₹50,000 cash and 1:4 leverage, you can buy stocks worth ₹2,00,000 — but a 25% loss wipes out your capital.',
    tags: ['leverage', 'borrow', 'risk', 'margin-call'],
    icon: '📊',
    relatedTerms: ['intraday', 'brokerage', 'risk-management'],
  },
  {
    id: 'brokerage',
    term: 'Brokerage',
    shortDefinition: 'Fee charged by a broker for executing trades.',
    detailedDefinition: `Brokerage is the fee that a stockbroker charges for executing buy and sell orders on your behalf. Discount brokers (Zerodha, Groww) charge low or zero brokerage for delivery trades but may charge for intraday and F&O trades. Full-service brokers charge higher fees but provide research and advisory services. Brokerage costs affect net trading profitability, especially for active traders.`,
    category: 'Trading',
    example: 'Zerodha charges ₹20 or 0.03% per trade, whichever is lower, on intraday and F&O trades.',
    tags: ['fee', 'broker', 'commission', 'discount-broker'],
    icon: '💼',
    relatedTerms: ['intraday', 'delivery-trading', 'stt'],
  },
  {
    id: 'stop-loss',
    term: 'Stop Loss',
    shortDefinition: 'A pre-set order to sell a stock when it reaches a certain price.',
    detailedDefinition: `A stop loss is an order placed with your broker to automatically sell a security when it reaches a specific price. It is a risk management tool that limits potential losses on a trade. For example, if you buy a stock at ₹100 and place a stop loss at ₹90, the stock will be automatically sold if it falls to ₹90. Stop losses protect traders from emotional decision-making during market volatility.`,
    category: 'Trading',
    example: 'A trader buys Nifty futures at 22,500 and sets a stop loss at 22,300 — maximum loss is limited to 200 points.',
    tags: ['risk-management', 'protection', 'order', 'exit'],
    icon: '🛑',
    relatedTerms: ['risk-management', 'margin-trading', 'intraday'],
  },
  {
    id: 'risk-management',
    term: 'Risk Management',
    shortDefinition: 'Strategies to identify, assess, and control trading risks.',
    detailedDefinition: `Risk management is the process of identifying, assessing, and controlling threats to your trading capital. Key principles include: never risk more than 1-2% of capital on a single trade, always use stop losses, diversify across sectors and asset classes, avoid over-leverage, and maintain a trading journal. Professional traders prioritize risk management over profit-making — they focus on preserving capital first.`,
    category: 'Trading',
    example: 'A disciplined trader with ₹10 lakh capital never risks more than ₹20,000 (2%) on any single trade.',
    tags: ['safety', 'capital-preservation', 'discipline', 'position-sizing'],
    icon: '🛡️',
    relatedTerms: ['stop-loss', 'margin-trading', 'diversification'],
  },
  {
    id: 'speculation',
    term: 'Speculation',
    shortDefinition: 'Trading based on anticipated price movements rather than fundamentals.',
    detailedDefinition: `Speculation involves buying or selling assets with the expectation of profiting from short-term price movements, often based on market sentiment, technical analysis, or news events rather than fundamental analysis. Speculation is higher risk than long-term investing and requires active monitoring. While speculation can generate quick profits, it requires discipline, risk management, and a proven trading system.`,
    category: 'Trading',
    example: 'A speculator buys weekly Nifty options before an RBI policy announcement, betting on a rate cut.',
    tags: ['short-term', 'trading', 'risk', 'momentum'],
    icon: '🎲',
    relatedTerms: ['intraday', 'derivatives', 'investing'],
  },
  {
    id: 'diversification',
    term: 'Diversification',
    shortDefinition: 'Spreading investments across different assets to reduce risk.',
    detailedDefinition: `Diversification is a risk management strategy that involves spreading investments across different asset classes (stocks, bonds, gold), sectors (IT, Pharma, Banking, Auto), and geographies. The goal is to reduce the impact of any single investment's poor performance on the overall portfolio. A well-diversified portfolio typically includes 15-20 stocks across 5-8 sectors. Diversification is the only free lunch in investing.`,
    category: 'Trading',
    example: 'A diversified portfolio has 60% equity (across sectors), 30% debt, and 10% gold for balanced risk.',
    tags: ['risk-reduction', 'portfolio', 'asset-allocation', 'balance'],
    icon: '🌈',
    relatedTerms: ['risk-management', 'asset-allocation', 'portfolio'],
  },
  {
    id: 'asset-allocation',
    term: 'Asset Allocation',
    shortDefinition: 'Dividing investments among different asset classes.',
    detailedDefinition: `Asset allocation is the strategy of dividing your investment portfolio among different asset classes such as equities, bonds, gold, real estate, and cash. It is the single most important determinant of long-term investment returns and volatility. A common rule is: 100 minus your age = percentage to invest in equities. Asset allocation should align with your financial goals, time horizon, and risk tolerance.`,
    category: 'Trading',
    example: 'A 30-year-old investor might allocate 70% to equities, 20% to debt, and 10% to gold.',
    tags: ['portfolio', 'balance', 'strategy', 'risk-profile'],
    icon: '📊',
    relatedTerms: ['diversification', 'risk-management', 'portfolio'],
  },

  // ═══════════════════ CRYPTO & DIGITAL ASSETS ═══════════════════
  {
    id: 'cryptocurrency',
    term: 'Cryptocurrency',
    shortDefinition: 'Digital or virtual currency secured by cryptography.',
    detailedDefinition: `Cryptocurrency is a digital or virtual currency that uses cryptography for security and operates on decentralized networks called blockchains. Unlike traditional currencies issued by governments (fiat), cryptocurrencies are not controlled by any central authority. Bitcoin (BTC), created in 2009, was the first cryptocurrency. Ethereum (ETH) introduced smart contracts, enabling decentralized applications. In India, cryptocurrencies are taxed at 30% under the Virtual Digital Assets (VDA) regime.`,
    category: 'Crypto & Digital Assets',
    example: 'An investor buys ₹50,000 worth of Bitcoin through a crypto exchange like CoinDCX or WazirX.',
    tags: ['bitcoin', 'ethereum', 'blockchain', 'digital-currency', 'vda'],
    icon: '₿',
    relatedTerms: ['blockchain', 'defi', 'capital-gains'],
  },
  {
    id: 'blockchain',
    term: 'Blockchain',
    shortDefinition: 'A decentralized, distributed ledger that records transactions.',
    detailedDefinition: `Blockchain is a distributed ledger technology where transaction records (blocks) are linked together using cryptography and stored across a network of computers. Each block contains a timestamp, transaction data, and a cryptographic hash of the previous block, making it virtually impossible to alter historical data. Beyond cryptocurrencies, blockchain has applications in supply chain, voting, identity verification, and smart contracts.`,
    category: 'Crypto & Digital Assets',
    example: 'A diamond retailer uses blockchain to track a gem from mine to store, proving its authenticity and origin.',
    tags: ['distributed-ledger', 'decentralized', 'crypto', 'smart-contracts'],
    icon: '🔗',
    relatedTerms: ['cryptocurrency', 'defi'],
  },
  {
    id: 'defi',
    term: 'Decentralized Finance (DeFi)',
    shortDefinition: 'Financial services built on blockchain without traditional intermediaries.',
    detailedDefinition: `Decentralized Finance (DeFi) refers to financial services and applications built on blockchain networks, primarily Ethereum, that operate without traditional intermediaries like banks, brokers, or insurance companies. DeFi offers lending, borrowing, trading, and yield farming through smart contracts. Users retain custody of their funds and interact directly with protocols. While DeFi offers high returns and accessibility, it carries risks like smart contract bugs, hacks, and regulatory uncertainty.`,
    category: 'Crypto & Digital Assets',
    example: 'A user deposits USDC into a DeFi lending protocol and earns 8% APY on their deposit, far higher than any bank FD.',
    tags: ['ethereum', 'smart-contracts', 'yield-farming', 'lending'],
    icon: '🏗️',
    relatedTerms: ['cryptocurrency', 'blockchain'],
  },
  {
    id: 'nft',
    term: 'Non-Fungible Token (NFT)',
    shortDefinition: 'A unique digital asset representing ownership of a specific item.',
    detailedDefinition: `An NFT (Non-Fungible Token) is a unique digital token on a blockchain that represents ownership of a specific item — artwork, music, collectibles, virtual real estate, or in-game assets. Unlike cryptocurrencies (which are fungible, like rupees), each NFT is one-of-a-kind and cannot be exchanged on a one-to-one basis. NFTs use the ERC-721 standard on Ethereum. While the NFT market peaked in 2021-22, the technology continues to find use in ticketing, certificates, and digital identity.`,
    category: 'Crypto & Digital Assets',
    example: 'An artist mints their digital artwork as an NFT and sells it for 10 ETH, with royalties programmed for future resales.',
    tags: ['token', 'digital-art', 'collectible', 'erc-721', 'ethereum'],
    icon: '🖼️',
    relatedTerms: ['cryptocurrency', 'blockchain'],
  },
  {
    id: 'web3',
    term: 'Web3',
    shortDefinition: 'The third generation of the internet, based on blockchain and decentralization.',
    detailedDefinition: `Web3 represents the next evolution of the internet, built on blockchain technology, where users own their data and digital assets rather than centralized corporations. Web3 applications (dApps) run on decentralized networks using cryptocurrencies, NFTs, and smart contracts. Key principles include permissionlessness (no gatekeepers), trustlessness (verifiable code), and self-sovereignty (users control their identity). While still emerging, Web3 has potential to transform finance, social media, gaming, and content creation.`,
    category: 'Crypto & Digital Assets',
    example: 'A Web3 social media platform lets users own their content and earn tokens for engagement, unlike traditional platforms.',
    tags: ['decentralized', 'dapp', 'smart-contracts', 'blockchain'],
    icon: '🌐',
    relatedTerms: ['cryptocurrency', 'blockchain', 'defi'],
  },

  // ═══════════════════ IPO (additional) ═══════════════════
  {
    id: 'anchor-investor',
    term: 'Anchor Investor',
    shortDefinition: 'Large institutional investor who invests in an IPO before it opens to the public.',
    detailedDefinition: `Anchor investors are large institutional investors (mutual funds, insurance companies, foreign investors) who commit to investing in an IPO before it opens to the general public. They are allocated shares at a price discovered through the book-building process, typically one day before the IPO opens. Anchor investors provide a credibility signal to retail investors — if sophisticated institutions are investing, it indicates confidence in the company. Anchor allocations are subject to a 30-day lock-in period.`,
    category: 'IPO',
    example: 'Before Zomato\'s IPO, 74 anchor investors including BlackRock and Fidelity invested ₹4,200 crore at the upper price band.',
    tags: ['institutional', 'book-building', 'qib', 'allocation'],
    icon: '⚓',
    relatedTerms: ['ipo', 'drhp'],
  },
  {
    id: 'shareholding-pattern',
    term: 'Shareholding Pattern',
    shortDefinition: 'Breakdown of who owns shares in a company.',
    detailedDefinition: `A shareholding pattern is a quarterly disclosure that shows the distribution of a company's shares among different categories of shareholders: promoters, foreign institutional investors (FIIs), domestic institutional investors (DIIs), mutual funds, retail investors, and others. Changes in shareholding pattern are closely watched by investors — increasing promoter holdings signal confidence, while rising FII/DII interest can drive stock prices. SEBI mandates quarterly disclosure of shareholding patterns.`,
    category: 'IPO',
    example: 'TCS released its June quarter shareholding pattern showing promoters hold 72%, FIIs 15%, and retail investors 8%.',
    tags: ['promoters', 'fii', 'dii', 'retail', 'disclosure'],
    icon: '📊',
    relatedTerms: ['ipo', 'fpo', 'fundamental-analysis'],
  },

  // ═══════════════════ BONDS & DEBT (additional) ═══════════════════
  {
    id: 'debenture',
    term: 'Debenture',
    shortDefinition: 'An unsecured debt instrument backed only by the issuer\'s creditworthiness.',
    detailedDefinition: `A debenture is a type of debt instrument that is not secured by physical assets or collateral. Unlike secured bonds (which are backed by specific assets), debentures rely solely on the issuer's creditworthiness and reputation. Because of the higher risk, debentures typically offer higher interest rates than secured bonds. In India, debentures are issued by companies to raise long-term funds and are traded on stock exchanges. Convertible debentures can be converted into equity shares at a future date.`,
    category: 'Bonds & Debt',
    example: 'A company issues ₹500 crore of debentures at 9.5% interest to fund its expansion, without pledging any assets.',
    tags: ['unsecured', 'debt', 'bond', 'convertible', 'corporate'],
    icon: '📃',
    relatedTerms: ['bond', 'yield', 'credit-rating', 'fixed-deposit'],
  },
  {
    id: 'fixed-deposit',
    term: 'Fixed Deposit (FD)',
    shortDefinition: 'A financial instrument offered by banks with a fixed interest rate.',
    detailedDefinition: `A Fixed Deposit (FD) is a financial instrument offered by banks and NBFCs where you deposit a lump sum for a fixed period at a predetermined interest rate. FDs offer guaranteed returns and are one of the safest investment options in India. Interest rates vary by tenure and institution (typically 3-8% per annum). Senior citizens get higher rates. FDs have a 5-year tax-saving variant under Section 80C. TDS is deducted on interest exceeding ₹40,000 per year (₹50,000 for senior citizens).`,
    category: 'Bonds & Debt',
    example: 'Depositing ₹1,00,000 in a 3-year FD at 7% interest yields approximately ₹22,500 in total interest.',
    tags: ['fd', 'bank', 'safe', 'guaranteed', 'tds'],
    icon: '🏦',
    relatedTerms: ['bond', 'interest-rate', 'tds', 'section-80c'],
  },
  {
    id: 'coupon-rate',
    term: 'Coupon Rate',
    shortDefinition: 'The annual interest rate paid by a bond or debenture.',
    detailedDefinition: `The coupon rate is the annual interest rate paid by a bond's issuer to the bondholder, expressed as a percentage of the bond's face value. For example, a bond with a face value of ₹1,000 and a coupon rate of 8% pays ₹80 in interest per year, usually in semi-annual installments. The coupon rate is fixed at the time of issuance and does not change. However, a bond's effective yield (current yield) changes as its market price fluctuates.`,
    category: 'Bonds & Debt',
    example: 'A 10-year government bond with 7% coupon rate pays ₹7,000 annually on a face value of ₹1,00,000.',
    tags: ['interest', 'bond', 'yield', 'fixed-income'],
    icon: '💳',
    relatedTerms: ['bond', 'yield', 'debenture'],
  },

  // ═══════════════════ GOLD & COMMODITIES (additional) ═══════════════════
  {
    id: 'silver',
    term: 'Silver',
    shortDefinition: 'A precious metal used as both an industrial metal and an investment.',
    detailedDefinition: `Silver is a precious metal that serves dual purposes — as an industrial metal (used in electronics, solar panels, and medical devices) and as an investment asset (coins, bars, ETFs). Silver is more volatile than gold due to its industrial demand component. In India, silver can be invested in physically (coins, bars), through Silver ETFs, or Silver Futures on MCX. Silver has historically outperformed gold during periods of industrial expansion.`,
    category: 'Gold & Commodities',
    example: 'An investor buys Silver ETF units to gain exposure to silver prices without the hassle of physical storage.',
    tags: ['precious-metal', 'industrial', 'etf', 'mcx'],
    icon: '🥈',
    relatedTerms: ['gold', 'commodity', 'etf'],
  },
  {
    id: 'crude-oil',
    term: 'Crude Oil',
    shortDefinition: 'A naturally occurring petroleum used as fuel and raw material.',
    detailedDefinition: `Crude oil is a naturally occurring fossil fuel that is refined into products like petrol, diesel, kerosene, and plastics. As a commodity, crude oil is one of the most actively traded assets globally. In India, crude oil futures trade on MCX. Oil prices significantly impact the Indian economy — India imports ~85% of its oil needs. Rising oil prices increase inflation, widen the trade deficit, and hurt sectors like aviation and transportation.`,
    category: 'Gold & Commodities',
    example: 'Brent crude oil rising from $75 to $95 per barrel increases India\'s import bill and can push fuel prices higher.',
    tags: ['commodity', 'energy', 'mcx', 'inflation', 'import'],
    icon: '🛢️',
    relatedTerms: ['commodity', 'inflation', 'gdp'],
  },

  // ═══════════════════ REAL ESTATE (additional) ═══════════════════
  {
    id: 'capital-gains-property',
    term: 'Capital Gains on Property',
    shortDefinition: 'Tax on profit from selling real estate.',
    detailedDefinition: `Capital gains on property arise when you sell a real estate asset at a profit. If the property is held for less than 24 months, it is Short-Term Capital Gains (STCG), taxed as per your income tax slab. If held for more than 24 months, it is Long-Term Capital Gains (LTCG), taxed at 20% with indexation benefit. LTCG on property can be saved by investing in specified bonds under Section 54EC (₹50 lakh limit) or buying another residential property under Section 54.`,
    category: 'Real Estate',
    example: 'Selling a house after 5 years for ₹80 lakh (bought for ₹50 lakh) — indexed cost ~₹59 lakh, so LTCG = ₹21 lakh taxed at 20%.',
    tags: ['property', 'tax', 'ltcg', 'stcg', 'indexation', '54ec'],
    icon: '🏘️',
    relatedTerms: ['real-estate', 'stcg', 'ltcg', 'capital-gains'],
  },
  {
    id: 'home-loan',
    term: 'Home Loan',
    shortDefinition: 'A loan taken to purchase a residential property.',
    detailedDefinition: `A home loan is a secured loan where you borrow money from a bank or NBFC to purchase a residential property, with the property itself serving as collateral. Home loans in India offer tenures up to 30 years with interest rates typically ranging from 8-12%. The loan-to-value (LTV) ratio allows borrowing up to 80-90% of the property value. Tax benefits include deduction of principal repayment under Section 80C (up to ₹1.5 lakh) and interest payment under Section 24 (up to ₹2 lakh for self-occupied property).`,
    category: 'Real Estate',
    example: 'A buyer takes a ₹40 lakh home loan at 9% interest for 20 years with an EMI of ~₹36,000 per month.',
    tags: ['property', 'mortgage', 'emi', '80c', 'tax-benefit'],
    icon: '🔑',
    relatedTerms: ['real-estate', 'section-80c', 'interest-rate'],
  },

  // ═══════════════════ MUTUAL FUNDS (additional) ═══════════════════
  {
    id: 'debt-fund',
    term: 'Debt Mutual Fund',
    shortDefinition: 'A mutual fund that invests in fixed-income instruments like bonds and T-bills.',
    detailedDefinition: `A debt mutual fund invests primarily in fixed-income instruments such as government securities (G-Secs), corporate bonds, treasury bills, commercial paper, and money market instruments. Debt funds are generally lower risk than equity funds and offer regular income. Categories include Liquid Funds (1-30 days), Ultra-Short Duration (3-6 months), Short Duration (1-3 years), and Gilt Funds (government securities). Returns are taxed as per your income tax slab for short-term (3 years or less) and at 20% with indexation for long-term.`,
    category: 'Mutual Funds',
    example: 'An investor parks ₹2,00,000 in a Liquid Fund for 3 months, earning ~5.5% annualized return with minimal risk.',
    tags: ['fixed-income', 'bond', 'liquid', 'low-risk', 'gilt'],
    icon: '📋',
    relatedTerms: ['mutual-fund', 'bond', 'expense-ratio', 'nav'],
  },
  {
    id: 'hybrid-fund',
    term: 'Hybrid Mutual Fund',
    shortDefinition: 'A mutual fund that invests in both equity and debt instruments.',
    detailedDefinition: `A hybrid mutual fund (also called balanced fund) invests in a mix of equity and debt instruments to provide both growth and stability. The allocation varies by category: Aggressive Hybrid Funds (65-80% equity), Conservative Hybrid Funds (10-25% equity), and Balanced Advantage Funds (dynamic allocation). Hybrid funds are ideal for investors who want a single diversified portfolio managed by professionals, with automatic rebalancing between asset classes based on market conditions.`,
    category: 'Mutual Funds',
    example: 'An aggressive hybrid fund with 75% equity and 25% debt delivered 14% returns in a bull year while cushioning downside in a bear year.',
    tags: ['balanced', 'equity', 'debt', 'diversified', 'allocation'],
    icon: '⚖️',
    relatedTerms: ['mutual-fund', 'debt-fund', 'asset-allocation', 'nav'],
  },

  // ═══════════════════ TECHNICAL ANALYSIS (additional) ═══════════════════
  {
    id: 'divergence',
    term: 'Divergence',
    shortDefinition: 'When price and an indicator (like RSI) move in opposite directions.',
    detailedDefinition: `Divergence occurs when the price of an asset moves in the opposite direction of a technical indicator like RSI or MACD. It signals weakening momentum and potential trend reversal. Bullish divergence happens when price makes a lower low but the indicator makes a higher low (selling pressure weakening). Bearish divergence occurs when price makes a higher high but the indicator makes a lower high (buying pressure weakening). Divergence is one of the most reliable signals in technical analysis.`,
    category: 'Technical Analysis',
    example: 'Nifty makes a new high at 25,200 while RSI makes a lower peak — bearish divergence warns of a potential pullback.',
    tags: ['indicator', 'reversal', 'momentum', 'rsi', 'macd'],
    icon: '↗️',
    relatedTerms: ['technical-analysis', 'rsi', 'macd'],
  },
  {
    id: 'trendline',
    term: 'Trendline',
    shortDefinition: 'A straight line connecting price points to identify the direction of a trend.',
    detailedDefinition: `A trendline is a straight line drawn on a price chart that connects two or more price points and extends into the future. An uptrend line connects higher swing lows (support), while a downtrend line connects lower swing highs (resistance). Trendlines help traders identify the trend direction, spot potential reversal points (when the line is broken), and set price targets. The more times a trendline is tested without breaking, the stronger it is considered.`,
    category: 'Technical Analysis',
    example: 'A trader draws an uptrend line connecting three higher lows on the Bank Nifty chart — as long as it holds, the uptrend is intact.',
    tags: ['chart', 'trend', 'support', 'resistance', 'drawing'],
    icon: '📉',
    relatedTerms: ['technical-analysis', 'support-resistance', 'breakout'],
  },

  // ═══════════════════ EQUITY (additional) ═══════════════════
  {
    id: 'rights-issue',
    term: 'Rights Issue',
    shortDefinition: 'Offering additional shares to existing shareholders at a discount.',
    detailedDefinition: `A rights issue is a corporate action where a company offers additional shares to its existing shareholders at a discounted price, in proportion to their current holdings. For example, a 1:2 rights issue means shareholders can buy 1 new share for every 2 they own. Rights issues are used to raise capital without involving new investors. Shareholders can either subscribe, sell their rights in the market, or let them lapse. Rights issues can lead to share price dilution if not fully subscribed.`,
    category: 'Equity',
    example: 'Yes Bank launched a ₹15,000 crore rights issue at a 40% discount to market price, offering 1 share for every 2 held.',
    tags: ['corporate-action', 'capital-raise', 'dilution', 'discount'],
    icon: '📄',
    relatedTerms: ['fpo', 'bonus-shares', 'stock-split'],
  },
  {
    id: 'preference-shares',
    term: 'Preference Shares',
    shortDefinition: 'Shares that receive dividends before common shareholders.',
    detailedDefinition: `Preference shares (or preferred stock) are a hybrid security that combines features of equity and debt. Preference shareholders receive dividends at a fixed rate before any dividend is paid to common equity shareholders. In case of liquidation, they have priority over common shareholders but rank below debt holders. Preference shares typically do not carry voting rights. They can be cumulative (unpaid dividends accumulate) or non-cumulative, and convertible or non-convertible.`,
    category: 'Equity',
    example: 'A company issues 10% cumulative preference shares — holders get ₹10 per share annual dividend before common shareholders.',
    tags: ['hybrid', 'dividend', 'fixed-income', 'preferred'],
    icon: '⭐',
    relatedTerms: ['equity', 'shares', 'dividend', 'debenture'],
  },
];
