import {
  User, MarketIndex, Stock, Holding, Trade, OpenOrder, Watchlist,
  MutualFund, SIPPlan, Course, Lesson, CommunityPost,
  AIInsight, Badge, UserLevel, AppNotification, MarketNewsItem,
  ChatRoom, ChatMessage, IPOItem, EconomicEvent, EarningsSummary, EarningsQuarter,
  StockSentiment, SentimentDataPoint, SentimentArticle
} from '../types';

// ============ User ============
export const mockUser: User = {
  id: 'user_1',
  name: 'Rahul Sharma',
  email: 'rahul.sharma@email.com',
  phone: '+91 98765 43210',
  panNumber: 'ABCDE1234F',
  avatar: undefined,
  kycStatus: 'verified',
  balance: 2500000,
  createdAt: '2024-01-15',
};

// ============ Market Indices ============
export const mockIndices: MarketIndex[] = [
  {
    id: 'nifty50',
    name: 'Nifty 50',
    shortName: 'NIFTY',
    currentValue: 23456.80,
    change: 345.20,
    changePercent: 1.49,
    isPositive: true,
    icon: 'trending-up',
  },
  {
    id: 'sensex',
    name: 'BSE Sensex',
    shortName: 'SENSEX',
    currentValue: 77123.45,
    change: -123.45,
    changePercent: -0.16,
    isPositive: false,
    icon: 'trending-down',
  },
  {
    id: 'banknifty',
    name: 'Bank Nifty',
    shortName: 'BANKNIFTY',
    currentValue: 49234.10,
    change: 567.89,
    changePercent: 1.17,
    isPositive: true,
    icon: 'trending-up',
  },
  {
    id: 'midcap',
    name: 'Nifty Midcap 100',
    shortName: 'MIDCAP',
    currentValue: 15678.90,
    change: 234.56,
    changePercent: 1.52,
    isPositive: true,
    icon: 'trending-up',
  },
];

// ============ Stocks ============
export const mockStocks: Stock[] = [
  {
    id: 'RELIANCE',
    symbol: 'RELIANCE',
    name: 'Reliance Industries Ltd.',
    sector: 'Energy',
    price: 2890.50,
    change: 45.20,
    changePercent: 1.59,
    isPositive: true,
    marketCap: '₹19,56,000 Cr',
    volume: '12.5M',
    high52: 3020.00,
    low52: 2200.00,
    pe: 28.5,
    pb: 3.2,
    dividend: 0.85,
  },
  {
    id: 'TCS',
    symbol: 'TCS',
    name: 'Tata Consultancy Services',
    sector: 'Technology',
    price: 3890.00,
    change: -34.50,
    changePercent: -0.88,
    isPositive: false,
    marketCap: '₹14,20,000 Cr',
    volume: '8.2M',
    high52: 4200.00,
    low52: 3300.00,
    pe: 35.2,
    pb: 12.5,
    dividend: 1.20,
  },
  {
    id: 'HDFCBANK',
    symbol: 'HDFCBANK',
    name: 'HDFC Bank Ltd.',
    sector: 'Finance',
    price: 1678.90,
    change: 23.45,
    changePercent: 1.42,
    isPositive: true,
    marketCap: '₹9,35,000 Cr',
    volume: '15.1M',
    high52: 1800.00,
    low52: 1360.00,
    pe: 18.9,
    pb: 2.8,
    dividend: 1.05,
  },
  {
    id: 'INFY',
    symbol: 'INFY',
    name: 'Infosys Ltd.',
    sector: 'Technology',
    price: 1567.80,
    change: 28.90,
    changePercent: 1.88,
    isPositive: true,
    marketCap: '₹6,52,000 Cr',
    volume: '10.8M',
    high52: 1700.00,
    low52: 1350.00,
    pe: 28.1,
    pb: 7.9,
    dividend: 1.80,
  },
  {
    id: 'ICICIBANK',
    symbol: 'ICICIBANK',
    name: 'ICICI Bank Ltd.',
    sector: 'Finance',
    price: 1123.45,
    change: -12.30,
    changePercent: -1.08,
    isPositive: false,
    marketCap: '₹7,85,000 Cr',
    volume: '18.5M',
    high52: 1250.00,
    low52: 980.00,
    pe: 16.5,
    pb: 2.3,
    dividend: 0.95,
  },
  {
    id: 'HINDUNILVR',
    symbol: 'HINDUNILVR',
    name: 'Hindustan Unilever Ltd.',
    sector: 'Consumer',
    price: 2567.30,
    change: -15.60,
    changePercent: -0.60,
    isPositive: false,
    marketCap: '₹6,03,000 Cr',
    volume: '5.2M',
    high52: 2800.00,
    low52: 2300.00,
    pe: 55.3,
    pb: 10.8,
    dividend: 1.50,
  },
  {
    id: 'BHARTIARTL',
    symbol: 'BHARTIARTL',
    name: 'Bharti Airtel Ltd.',
    sector: 'Telecom',
    price: 1345.60,
    change: 34.50,
    changePercent: 2.63,
    isPositive: true,
    marketCap: '₹7,50,000 Cr',
    volume: '9.8M',
    high52: 1450.00,
    low52: 1050.00,
    pe: 42.1,
    pb: 5.6,
    dividend: 0.45,
  },
  {
    id: 'SBIN',
    symbol: 'SBIN',
    name: 'State Bank of India',
    sector: 'Finance',
    price: 789.50,
    change: 15.80,
    changePercent: 2.04,
    isPositive: true,
    marketCap: '₹7,04,000 Cr',
    volume: '22.3M',
    high52: 850.00,
    low52: 640.00,
    pe: 10.2,
    pb: 1.5,
    dividend: 2.15,
  },
  {
    id: 'TATAMOTORS',
    symbol: 'TATAMOTORS',
    name: 'Tata Motors Ltd.',
    sector: 'Automobile',
    price: 945.20,
    change: -8.90,
    changePercent: -0.93,
    isPositive: false,
    marketCap: '₹3,12,000 Cr',
    volume: '14.6M',
    high52: 1100.00,
    low52: 780.00,
    pe: 8.5,
    pb: 2.1,
    dividend: 0.35,
  },
  {
    id: 'BAJFINANCE',
    symbol: 'BAJFINANCE',
    name: 'Bajaj Finance Ltd.',
    sector: 'Finance',
    price: 6789.00,
    change: 123.40,
    changePercent: 1.85,
    isPositive: true,
    marketCap: '₹4,12,000 Cr',
    volume: '6.8M',
    high52: 7500.00,
    low52: 5800.00,
    pe: 32.4,
    pb: 5.2,
    dividend: 0.60,
  },
  {
    id: 'WIPRO',
    symbol: 'WIPRO',
    name: 'Wipro Ltd.',
    sector: 'Technology',
    price: 456.30,
    change: 8.70,
    changePercent: 1.94,
    isPositive: true,
    marketCap: '₹2,40,000 Cr',
    volume: '11.2M',
    high52: 520.00,
    low52: 380.00,
    pe: 24.3,
    pb: 4.1,
    dividend: 0.75,
  },
  {
    id: 'ITC',
    symbol: 'ITC',
    name: 'ITC Ltd.',
    sector: 'Consumer',
    price: 478.90,
    change: -5.60,
    changePercent: -1.16,
    isPositive: false,
    marketCap: '₹5,98,000 Cr',
    volume: '20.5M',
    high52: 510.00,
    low52: 400.00,
    pe: 26.8,
    pb: 6.3,
    dividend: 2.50,
  },
];

// ============ Portfolio Holdings ============
export const mockHoldings: Holding[] = [
  {
    id: 'h1',
    stockId: 'RELIANCE',
    symbol: 'RELIANCE',
    name: 'Reliance Industries Ltd.',
    quantity: 50,
    buyPrice: 2650.00,
    currentPrice: 2890.50,
    totalInvested: 132500,
    currentValue: 144525,
    pnl: 12025,
    pnlPercent: 9.08,
    dayChange: 2260,
    dayChangePercent: 1.59,
  },
  {
    id: 'h2',
    stockId: 'HDFCBANK',
    symbol: 'HDFCBANK',
    name: 'HDFC Bank Ltd.',
    quantity: 100,
    buyPrice: 1550.00,
    currentPrice: 1678.90,
    totalInvested: 155000,
    currentValue: 167890,
    pnl: 12890,
    pnlPercent: 8.32,
    dayChange: 2345,
    dayChangePercent: 1.42,
  },
  {
    id: 'h3',
    stockId: 'TCS',
    symbol: 'TCS',
    name: 'Tata Consultancy Services',
    quantity: 20,
    buyPrice: 3800.00,
    currentPrice: 3890.00,
    totalInvested: 76000,
    currentValue: 77800,
    pnl: 1800,
    pnlPercent: 2.37,
    dayChange: -690,
    dayChangePercent: -0.88,
  },
  {
    id: 'h4',
    stockId: 'INFY',
    symbol: 'INFY',
    name: 'Infosys Ltd.',
    quantity: 80,
    buyPrice: 1450.00,
    currentPrice: 1567.80,
    totalInvested: 116000,
    currentValue: 125424,
    pnl: 9424,
    pnlPercent: 8.12,
    dayChange: 2312,
    dayChangePercent: 1.88,
  },
  {
    id: 'h5',
    stockId: 'SBIN',
    symbol: 'SBIN',
    name: 'State Bank of India',
    quantity: 200,
    buyPrice: 720.00,
    currentPrice: 789.50,
    totalInvested: 144000,
    currentValue: 157900,
    pnl: 13900,
    pnlPercent: 9.65,
    dayChange: 3160,
    dayChangePercent: 2.04,
  },
];

// ============ Recent Trades ============
export const mockTrades: Trade[] = [
  { id: 't1', stockId: 'RELIANCE', symbol: 'RELIANCE', name: 'Reliance Industries', type: 'buy', quantity: 50, price: 2650.00, total: 132500, timestamp: '2025-05-20T09:30:00' },
  { id: 't2', stockId: 'TCS', symbol: 'TCS', name: 'Tata Consultancy Services', type: 'sell', quantity: 10, price: 3920.00, total: 39200, timestamp: '2025-05-19T14:45:00' },
  { id: 't3', stockId: 'HDFCBANK', symbol: 'HDFCBANK', name: 'HDFC Bank', type: 'buy', quantity: 100, price: 1550.00, total: 155000, timestamp: '2025-05-18T11:20:00' },
  { id: 't4', stockId: 'INFY', symbol: 'INFY', name: 'Infosys', type: 'buy', quantity: 80, price: 1450.00, total: 116000, timestamp: '2025-05-17T10:15:00' },
  { id: 't5', stockId: 'SBIN', symbol: 'SBIN', name: 'State Bank of India', type: 'buy', quantity: 200, price: 720.00, total: 144000, timestamp: '2025-05-16T09:45:00' },
];

// ============ Watchlists ============
export const mockWatchlists: Watchlist[] = [
  {
    id: 'w1',
    name: 'My Watchlist',
    stocks: [mockStocks[0], mockStocks[3], mockStocks[7], mockStocks[9]],
    createdAt: '2025-01-10',
  },
  {
    id: 'w2',
    name: 'Tech Stocks',
    stocks: [mockStocks[1], mockStocks[3], mockStocks[10]],
    createdAt: '2025-02-15',
  },
];

// ============ Mutual Funds ============
export const mockMutualFunds: MutualFund[] = [
  { id: 'mf1', name: 'Parag Parikh Flexi Cap Fund', category: 'Flexi Cap', nav: 67.45, dayChange: 0.89, dayChangePercent: 1.34, oneYearReturn: 28.5, threeYearReturn: 72.3, fiveYearReturn: 125.6, riskLevel: 'high', minInvestment: 1000, fundSize: '₹45,678 Cr', rating: 5 },
  { id: 'mf2', name: 'HDFC Mid-Cap Opportunities Fund', category: 'Mid Cap', nav: 156.30, dayChange: 1.23, dayChangePercent: 0.79, oneYearReturn: 35.2, threeYearReturn: 85.6, fiveYearReturn: 145.8, riskLevel: 'high', minInvestment: 500, fundSize: '₹32,456 Cr', rating: 4 },
  { id: 'mf3', name: 'SBI Bluechip Fund', category: 'Large Cap', nav: 89.20, dayChange: -0.45, dayChangePercent: -0.50, oneYearReturn: 22.1, threeYearReturn: 58.4, fiveYearReturn: 98.2, riskLevel: 'moderate', minInvestment: 500, fundSize: '₹28,912 Cr', rating: 4 },
  { id: 'mf4', name: 'Axis Small Cap Fund', category: 'Small Cap', nav: 112.80, dayChange: 2.15, dayChangePercent: 1.94, oneYearReturn: 42.3, threeYearReturn: 95.7, fiveYearReturn: 168.4, riskLevel: 'high', minInvestment: 500, fundSize: '₹18,567 Cr', rating: 5 },
  { id: 'mf5', name: 'ICICI Prudential Value Discovery Fund', category: 'Value', nav: 178.60, dayChange: 1.56, dayChangePercent: 0.88, oneYearReturn: 25.8, threeYearReturn: 62.1, fiveYearReturn: 110.5, riskLevel: 'moderate', minInvestment: 1000, fundSize: '₹22,345 Cr', rating: 4 },
  { id: 'mf6', name: 'Kotak Corporate Bond Fund', category: 'Debt', nav: 45.90, dayChange: 0.12, dayChangePercent: 0.26, oneYearReturn: 8.2, threeYearReturn: 22.5, fiveYearReturn: 38.7, riskLevel: 'low', minInvestment: 1000, fundSize: '₹15,234 Cr', rating: 3 },
];

export const mockSIPs: SIPPlan[] = [
  { id: 'sip1', fundId: 'mf1', fundName: 'Parag Parikh Flexi Cap Fund', amount: 5000, frequency: 'monthly', nextDate: '2025-06-01', totalInvested: 60000, currentValue: 68450, returns: 8450 },
  { id: 'sip2', fundId: 'mf3', fundName: 'SBI Bluechip Fund', amount: 3000, frequency: 'monthly', nextDate: '2025-06-05', totalInvested: 36000, currentValue: 39120, returns: 3120 },
];

// ============ Learning Paths ============
import type { LearningPath } from '../types';

/**
 * Curated learning paths that group courses into sequences.
 * Each path takes the user from fundamentals to advanced concepts.
 */
export const mockLearningPaths: LearningPath[] = [
  {
    id: 'path_beginner',
    title: 'Investing Fundamentals',
    description: 'Start your investment journey from scratch. Learn stock market basics, personal finance, and SIP investing. Perfect for absolute beginners.',
    icon: '🌱',
    gradient: ['#00E676', '#009624'],
    level: 'beginner',
    courseIds: ['c7', 'c12', 'c1', 'c4'],
    enrolledCount: 28400,
    totalDuration: '17 hours',
    totalLessons: 26,
    targetAudience: 'Complete beginners with zero trading experience. No prior knowledge required.',
    skillsGained: ['Stock Market Basics', 'Personal Finance', 'Mutual Fund Selection', 'SIP Planning', 'IPO Investing'],
  },
  {
    id: 'path_intermediate',
    title: 'Technical & Fundamental Trader',
    description: 'Level up with professional analysis techniques. Master technical analysis, fundamental analysis, and risk management.',
    icon: '📊',
    gradient: ['#6C63FF', '#3F3D99'],
    level: 'intermediate',
    courseIds: ['c2', 'c3', 'c6', 'c10', 'c14'],
    enrolledCount: 18200,
    totalDuration: '30 hours',
    totalLessons: 36,
    targetAudience: 'Investors who understand basics and want to learn professional analysis methods.',
    skillsGained: ['Technical Analysis', 'Candlestick Patterns', 'Fundamental Analysis', 'DCF Valuation', 'Risk Management', 'Tax Planning'],
  },
  {
    id: 'path_advanced',
    title: 'Options & Portfolio Pro',
    description: 'Go pro with advanced options strategies, behavioral finance, and professional portfolio management.',
    icon: '🎯',
    gradient: ['#FF5252', '#D50000'],
    level: 'advanced',
    courseIds: ['c5', 'c13', 'c9', 'c11'],
    enrolledCount: 8900,
    totalDuration: '23 hours',
    totalLessons: 26,
    targetAudience: 'Experienced traders ready for advanced options strategies and institutional-level portfolio management.',
    skillsGained: ['Options Strategies', 'Greeks & Pricing', 'Portfolio Management', 'Asset Allocation', 'Behavioral Finance'],
  },
];

// ============ Education ============
import { realCourses, realLessons } from './courseContent';

// Re-export the real course content
export const mockCourses: Course[] = realCourses;
export const mockLessons: Lesson[] = realLessons;

// ============ Community ============
export const mockPosts: CommunityPost[] = [
  { id: 'p1', userId: 'u2', userName: 'Priya Patel', content: 'Just made my first 1 lakh profit on RELIANCE calls! 🚀 The technical setup was perfect with the breakout above 2850.', likes: 245, comments: 38, timestamp: '2025-05-24T10:30:00', tags: ['RELIANCE', 'Options', 'Profit'] },
  { id: 'p2', userId: 'u3', userName: 'Arun Kumar', content: 'Anyone else looking at ITC? The valuation looks attractive at current levels. 4% dividend yield is a bonus! 📊', likes: 89, comments: 24, timestamp: '2025-05-24T09:15:00', tags: ['ITC', 'ValueInvesting', 'Dividend'] },
  { id: 'p3', userId: 'u4', userName: 'Neha Singh', content: 'Started my first SIP today! ₹5000/month in Parag Parikh Flexi Cap Fund. Better late than never! 💪 #StartSmall', likes: 178, comments: 42, timestamp: '2025-05-23T18:45:00', tags: ['SIP', 'MutualFunds', 'Beginner'] },
  { id: 'p4', userId: 'u5', userName: 'Vikram Reddy', content: 'Market outlook this week: Nifty facing resistance at 23500. If it breaks, we could see 23800. Support at 23100. Trade carefully! 🎯', likes: 312, comments: 56, timestamp: '2025-05-23T08:00:00', tags: ['Nifty', 'MarketOutlook', 'Analysis'] },
  { id: 'p5', userId: 'u6', userName: 'Sneha Kapoor', content: 'Just completed the Technical Analysis course on this app! Amazing content. Highly recommend it for beginners who want to learn chart patterns. 📚', likes: 134, comments: 19, timestamp: '2025-05-22T20:30:00', tags: ['Learning', 'TechnicalAnalysis', 'Review'] },
];

// ============ AI Insights ============
export const mockAIInsights: AIInsight[] = [
  {
    id: 'ai1', stockId: 'RELIANCE', symbol: 'RELIANCE', name: 'Reliance Industries', type: 'bullish', confidence: 85,
    summary: 'Strong breakout above resistance with high volume',
    analysis: 'RELIANCE has broken above the key resistance level of ₹2,850 with significantly higher volumes than the 20-day average. The RSI is at 62, indicating room for further upside. The stock is trading above all major moving averages (50, 100, 200 DMA). Strong support from institutional buying observed.',
    targets: [{ target: 2950, probability: 75 }, { target: 3020, probability: 45 }, { target: 3100, probability: 25 }],
    timestamp: '2025-05-24T08:00:00',
  },
  {
    id: 'ai2', stockId: 'TCS', symbol: 'TCS', name: 'Tata Consultancy Services', type: 'bearish', confidence: 72,
    summary: 'Forming lower highs; weak momentum',
    analysis: 'TCS is showing signs of weakness with a series of lower highs on the daily chart. The MACD has given a sell signal. The IT sector is facing headwinds from a strong rupee and potential US spending cuts. Key support at ₹3,800 needs to hold.',
    targets: [{ target: 3800, probability: 60 }, { target: 3650, probability: 35 }, { target: 3500, probability: 15 }],
    timestamp: '2025-05-24T08:00:00',
  },
  {
    id: 'ai3', stockId: 'HDFCBANK', symbol: 'HDFCBANK', name: 'HDFC Bank', type: 'neutral', confidence: 65,
    summary: 'Consolidating in a range; wait for breakout',
    analysis: 'HDFC Bank is consolidating between ₹1,650 and ₹1,720. The stock needs to break above ₹1,720 for a bullish move or below ₹1,650 for a bearish move. The merger synergies are playing out well, but NIM compression is a near-term concern.',
    targets: [{ target: 1720, probability: 55 }, { target: 1800, probability: 35 }, { target: 1600, probability: 20 }],
    timestamp: '2025-05-24T08:00:00',
  },
  {
    id: 'ai4', stockId: 'SBIN', symbol: 'SBIN', name: 'State Bank of India', type: 'bullish', confidence: 88,
    summary: 'Strong uptrend with high institutional interest',
    analysis: 'SBI is in a strong uptrend, up 9.65% from your buy price. The PSU banking sector is seeing strong momentum. The stock has support at ₹760 and next resistance at ₹820. Strong quarterly results with improving asset quality are driving the rally.',
    targets: [{ target: 820, probability: 80 }, { target: 850, probability: 55 }, { target: 900, probability: 30 }],
    timestamp: '2025-05-24T08:00:00',
  },
];

// ============ Gamification ============
export const mockBadges: Badge[] = [
  { id: 'b1', name: 'First Trade', description: 'Placed your first trade', icon: '🎯', requirement: 'Place your first trade', unlocked: true, unlockedAt: '2025-02-01' },
  { id: 'b2', name: 'Market Explorer', description: 'Explored all sections of the app', icon: '🧭', requirement: 'Visit all app sections', unlocked: true, unlockedAt: '2025-02-05' },
  { id: 'b3', name: 'Profit Hunter', description: 'Made your first profit on a trade', icon: '💰', requirement: 'Book profit on any trade', unlocked: true, unlockedAt: '2025-03-15' },
  { id: 'b4', name: 'Steady Investor', description: 'Maintained a portfolio for 30 days', icon: '🛡️', requirement: 'Hold portfolio for 30 days', unlocked: true, unlockedAt: '2025-03-20' },
  { id: 'b5', name: 'Learner', description: 'Completed 5 lessons', icon: '📚', requirement: 'Complete 5 lessons', unlocked: true, unlockedAt: '2025-04-10' },
  { id: 'b6', name: 'SIP Champion', description: 'Started your first SIP', icon: '🏆', requirement: 'Start a SIP investment', unlocked: true, unlockedAt: '2025-04-15' },
  { id: 'b7', name: 'Diamond Hands', description: 'Held a stock through a market crash', icon: '💎', requirement: 'Hold during 5% market drop', unlocked: false },
  { id: 'b8', name: 'Community Star', description: 'Got 100 likes on your posts', icon: '⭐', requirement: 'Reach 100 total likes', unlocked: false },
  { id: 'b9', name: 'Options Master', description: 'Successfully traded options', icon: '🎓', requirement: 'Place 10 options trades', unlocked: false },
  { id: 'b10', name: 'Wealth Builder', description: 'Reach ₹10L portfolio value', icon: '🏦', requirement: 'Portfolio value exceeds ₹10L', unlocked: false },
  { id: 'b11', name: 'Analyst', description: 'Used AI insights for 5 trades', icon: '🔮', requirement: 'Follow 5 AI recommendations', unlocked: false },
  { id: 'b12', name: 'Quiz Whiz', description: 'Score 100% on any quiz', icon: '🧠', requirement: 'Get full marks in a quiz', unlocked: false },
];

export const mockUserLevel: UserLevel = {
  level: 12,
  title: 'Trading Pro',
  xp: 4500,
  xpToNext: 5000,
  totalXp: 24500,
};

// ============ Notifications ============
export const mockNotifications: AppNotification[] = [
  { id: 'n1', type: 'price_alert', title: 'Price Alert: RELIANCE', message: 'RELIANCE crossed ₹2,890. Target 1 achieved! 🎯', read: false, timestamp: '2025-05-24T10:00:00' },
  { id: 'n2', type: 'trade', title: 'Trade Executed', message: 'Buy order for 50 RELIANCE @ ₹2,890 executed successfully.', read: false, timestamp: '2025-05-24T09:35:00' },
  { id: 'n3', type: 'educational', title: 'New Lesson Available', message: 'Next lesson "Advanced Chart Patterns" is ready for you!', read: true, timestamp: '2025-05-23T12:00:00' },
  { id: 'n4', type: 'news', title: 'Market News: RBI Policy', message: 'RBI keeps repo rate unchanged at 6.50%. Markets react positively.', read: true, timestamp: '2025-05-23T10:00:00' },
  { id: 'n5', type: 'system', title: 'KYC Update', message: 'Your KYC documents have been verified successfully! ✅', read: true, timestamp: '2025-05-20T14:00:00' },
];

// ============ Open Orders (Mock) ============
export const mockOpenOrders: OpenOrder[] = [
  {
    id: 'open_ord_1',
    symbol: 'RELIANCE',
    exchange: 'NSE',
    transactionType: 'BUY',
    quantity: 25,
    filledQuantity: 0,
    price: 2850.00,
    productType: 'CNC',
    orderType: 'LIMIT',
    status: 'open',
    placedBy: 'WEB',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    validity: 'DAY',
  },
  {
    id: 'open_ord_2',
    symbol: 'TCS',
    exchange: 'NSE',
    transactionType: 'SELL',
    quantity: 10,
    filledQuantity: 5,
    price: 3950.00,
    productType: 'CNC',
    orderType: 'LIMIT',
    status: 'partially_filled',
    placedBy: 'WEB',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    validity: 'DAY',
  },
  {
    id: 'open_ord_3',
    symbol: 'INFY',
    exchange: 'NSE',
    transactionType: 'BUY',
    quantity: 50,
    filledQuantity: 0,
    price: 1550.00,
    triggerPrice: 1540.00,
    productType: 'MIS',
    orderType: 'SL',
    status: 'trigger_pending',
    placedBy: 'WEB',
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    validity: 'DAY',
  },
  {
    id: 'open_ord_4',
    symbol: 'HDFCBANK',
    exchange: 'NSE',
    transactionType: 'BUY',
    quantity: 30,
    filledQuantity: 0,
    price: 1660.00,
    productType: 'CNC',
    orderType: 'LIMIT',
    status: 'pending',
    placedBy: 'WEB',
    timestamp: new Date(Date.now() - 1800000).toISOString(),
    validity: 'DAY',
  },
];

// ============ Market News ============
export const mockNews: MarketNewsItem[] = [
  {
    id: 'news_1',
    title: 'RBI Keeps Repo Rate Unchanged at 6.50% — Markets Rally',
    summary: 'The Reserve Bank of India maintained status quo on key policy rates for the seventh consecutive meeting, highlighting easing inflation but caution on food prices.',
    content: 'The Monetary Policy Committee (MPC) voted 4-2 to keep the repo rate unchanged at 6.50%, in line with market expectations. RBI Governor Shaktikanta Das highlighted that while inflation has moderated, upside risks from food prices remain. The GDP growth forecast for FY26 was maintained at 7.2%. Banking and auto stocks led the rally post-announcement, with Nifty closing 1.5% higher. The RBI also announced measures to boost liquidity in the banking system.',
    source: 'Economic Times',
    category: 'policy',
    sentiment: 'positive',
    publishedAt: '2025-05-28T10:30:00',
    read: false,
    bookmarked: false,
  },
  {
    id: 'news_2',
    title: 'Reliance Industries Q4 Net Profit Rises 12% to ₹21,345 Cr',
    summary: 'Reliance Industries reported a 12% YoY increase in consolidated net profit, driven by strong performance in retail and telecom segments.',
    content: 'Reliance Industries Ltd (RIL) reported a consolidated net profit of ₹21,345 crore for the March quarter, beating analyst estimates. Revenue from operations rose 8% to ₹2.41 lakh crore. The retail segment posted 18% revenue growth, while Jio added 11 million new subscribers. The O2C segment faced margin pressure due to weaker refining margins. RIL announced a dividend of ₹10 per share. Shares of RIL reacted positively, gaining 3% in early trade.',
    source: 'Moneycontrol',
    category: 'corporate',
    symbol: 'RELIANCE',
    sentiment: 'positive',
    publishedAt: '2025-05-27T08:15:00',
    read: false,
    bookmarked: true,
  },
  {
    id: 'news_3',
    title: 'SEBI Proposes Stricter F&O Entry Barriers for Retail Investors',
    summary: 'Market regulator SEBI has proposed higher contract sizes and increased margin requirements for futures and options trading to curb speculative activity.',
    content: 'The Securities and Exchange Board of India (SEBI) released a consultation paper proposing stricter norms for retail participation in the derivatives segment. Key proposals include: increasing the minimum contract size from ₹5 lakh to ₹15 lakh, raising extreme loss margin (ELM) requirements, and introducing additional position limits for index derivatives. Market participants expressed mixed reactions, with some calling it a necessary step to protect retail investors while others warned of reduced liquidity. The F&O segment has seen explosive growth, with notional turnover exceeding ₹500 lakh crore in FY25.',
    source: 'Business Standard',
    category: 'markets',
    sentiment: 'negative',
    publishedAt: '2025-05-26T14:00:00',
    read: true,
    bookmarked: false,
  },
  {
    id: 'news_4',
    title: 'HDFC Bank, ICICI Bank Lead Banking Rally as Nifty Bank Hits Fresh High',
    summary: 'The Nifty Bank index surged to a new all-time high, led by strong gains in HDFC Bank and ICICI Bank after robust Q4 earnings.',
    content: "The banking index rallied 3.5% to hit a fresh record high of 49,567, surpassing its previous peak set in January 2025. HDFC Bank gained 4.2% after reporting its highest-ever quarterly net profit, while ICICI Bank rose 3.8% following strong NII growth. The rally was broad-based with all PSU banks also contributing. Analysts attribute the strength to improving asset quality, healthy credit growth, and stable margins. The RBI's status quo on rates provided additional tailwinds for the sector.",
    source: 'CNBC TV18',
    category: 'markets',
    symbol: 'HDFCBANK',
    sentiment: 'positive',
    publishedAt: '2025-05-26T11:30:00',
    read: true,
    bookmarked: false,
  },
  {
    id: 'news_5',
    title: 'Crude Oil Prices Dip Below $80 on OPEC+ Supply Increase Signals',
    summary: 'Global crude oil prices fell below $80 per barrel after reports that OPEC+ may begin unwinding production cuts from October.',
    content: "Brent crude futures dropped 3.2% to $78.50 per barrel following reports that OPEC+ is considering gradually increasing supply from October 2025. The cartel had been maintaining production cuts of 2.2 million barrels per day. Saudi Arabia's energy minister signalled willingness to bring back supply if market conditions remain stable. The decline in oil prices is positive for oil-importing countries like India, potentially easing inflationary pressures and reducing the import bill.",
    source: 'Reuters',
    category: 'global',
    sentiment: 'neutral',
    publishedAt: '2025-05-25T22:00:00',
    read: true,
    bookmarked: false,
  },
  {
    id: 'news_6',
    title: 'Tata Motors, M&M Lead Auto Sector Surge on Strong April Sales Data',
    summary: 'Automobile stocks rallied after companies reported robust April sales numbers, with passenger vehicles segment posting double-digit growth.',
    content: 'Shares of Tata Motors gained 5.5% while M&M rose 4.8% after both companies reported strong domestic sales figures for April 2025. Tata Motors reported total sales of 89,000 units, up 15% YoY, driven by strong demand for its SUV portfolio. M&M sold 72,000 SUVs, recording 18% growth. Maruti Suzuki also reported a 9% increase in total sales. The auto sector continues to benefit from strong rural demand, new model launches, and stable commodity prices.',
    source: 'Financial Express',
    category: 'corporate',
    symbol: 'TATAMOTORS',
    sentiment: 'positive',
    publishedAt: '2025-05-25T09:45:00',
    read: false,
    bookmarked: false,
  },
  {
    id: 'news_7',
    title: 'IT Stocks Under Pressure as US Client Spending Concerns Mount',
    summary: 'Indian IT stocks faced selling pressure amid concerns over reduced technology spending by US clients due to economic uncertainty.',
    content: 'The Nifty IT index declined 2.8% as major IT stocks came under selling pressure. TCS fell 2.5%, Infosys dropped 3.1%, and Wipro declined 2.8%. Analysts cited concerns over reduced discretionary spending by US clients, potential visa policy changes, and margin pressure from wage hikes. However, most brokerages maintain a positive long-term view on the sector, citing strong deal pipelines and the potential benefit from a weaker rupee. The US accounts for 60-65% of revenue for major Indian IT firms.',
    source: 'Bloomberg Quint',
    category: 'markets',
    symbol: 'TCS',
    sentiment: 'negative',
    publishedAt: '2025-05-24T15:30:00',
    read: false,
    bookmarked: false,
  },
  {
    id: 'news_8',
    title: 'IPO Corner: LG Electronics India Files DRHP for ₹15,000 Cr Issue',
    summary: 'LG Electronics India has filed its draft red herring prospectus with SEBI for an initial public offering worth approximately ₹15,000 crore.',
    content: 'LG Electronics India, the Indian subsidiary of the South Korean conglomerate, has filed its DRHP for an IPO comprising an offer for sale of up to 15 crore shares by the parent company. The issue is expected to raise around ₹15,000 crore, making it one of the largest IPOs in India in 2025. The company plans to use the proceeds for brand building and expansion. LG India is the market leader in consumer durables with a 25% market share in the AC segment and 22% in refrigerators. The IPO is expected to open in Q3 FY26.',
    source: 'Livemint',
    category: 'ipo',
    sentiment: 'positive',
    publishedAt: '2025-05-24T07:00:00',
    read: false,
    bookmarked: false,
  },
  {
    id: 'news_9',
    title: "India's GDP Growth Set to Remain Strong at 7.2%: IMF",
    summary: "The International Monetary Fund has retained India's GDP growth forecast at 7.2% for FY26, making India the fastest-growing major economy.",
    content: "The IMF's latest World Economic Outlook update projects India's GDP growth at 7.2% for FY26 and 7.0% for FY27. The global body highlighted India's robust domestic demand, structural reforms, and digital infrastructure as key growth drivers. However, it cautioned about risks from global trade fragmentation, geopolitical tensions, and climate-related disruptions. India's growth remains well above the global average of 3.2% and China's projected 4.6% growth, cementing its position as the fastest-growing major economy.",
    source: 'The Hindu Business Line',
    category: 'economy',
    sentiment: 'positive',
    publishedAt: '2025-05-23T12:00:00',
    read: true,
    bookmarked: false,
  },
  {
    id: 'news_10',
    title: 'Zomato, Paytm, Nykaa: New-Age Tech Stocks See Profit Booking After Rally',
    summary: 'New-age technology stocks witnessed profit booking after a sharp rally, with Zomato, Paytm, and Nykaa declining 3-5% each.',
    content: 'After a spectacular run-up over the past three months, new-age technology stocks saw significant profit booking. Zomato fell 5.2%, Paytm declined 4.5%, and Nykaa dropped 3.8%. The Nifty New Age Tech index corrected 3.5%. Analysts attribute the sell-off to valuation concerns and profit-taking ahead of the quarterly expiry. Despite the correction, most of these stocks are still trading 20-40% higher than their 52-week lows. Market experts advise investors to focus on fundamentals and not get carried away by the recent rally.',
    source: 'ET Markets',
    category: 'markets',
    sentiment: 'negative',
    publishedAt: '2025-05-23T09:30:00',
    read: false,
    bookmarked: false,
  },
];

// ============ Chart History (Mock) ============

// ============ Chat Rooms & Messages ============
const now = Date.now();
const h = (hours: number) => hours * 60 * 60 * 1000;

export const mockChatRooms: ChatRoom[] = [
  {
    id: 'room_1',
    name: 'Trading Legends',
    type: 'group',
    topic: 'Technical Analysis & Strategies',
    lastMessage: 'Nifty support at 23400, watch for bounce',
    lastMessageTime: new Date(now - h(0.5)).toISOString(),
    lastMessageSender: 'Arun Kumar',
    unreadCount: 3,
    participants: [
      { userId: 'user_2', userName: 'Arun Kumar', isOnline: true },
      { userId: 'user_3', userName: 'Priya Patel', isOnline: true },
      { userId: 'user_4', userName: 'Neha Singh', isOnline: false },
      { userId: 'user_5', userName: 'Vikram Reddy', isOnline: true },
    ],
  },
  {
    id: 'room_2',
    name: 'RELIANCE Discussion',
    type: 'group',
    topic: 'Reliance stock analysis and news',
    stockSymbol: 'RELIANCE',
    lastMessage: 'Q4 results next week, expectations?',
    lastMessageTime: new Date(now - h(2)).toISOString(),
    lastMessageSender: 'Rahul Sharma',
    unreadCount: 0,
    participants: [
      { userId: 'user_6', userName: 'Sneha Kapoor', isOnline: false },
      { userId: 'user_2', userName: 'Arun Kumar', isOnline: true },
    ],
  },
  {
    id: 'room_3',
    name: 'Options Strategies',
    type: 'group',
    topic: 'F&O trading strategies and risk management',
    lastMessage: 'Iron condor on Nifty works best in range-bound markets',
    lastMessageTime: new Date(now - h(5)).toISOString(),
    lastMessageSender: 'Vikram Reddy',
    unreadCount: 1,
    participants: [
      { userId: 'user_3', userName: 'Priya Patel', isOnline: true },
      { userId: 'user_4', userName: 'Neha Singh', isOnline: false },
      { userId: 'user_5', userName: 'Vikram Reddy', isOnline: true },
      { userId: 'user_6', userName: 'Sneha Kapoor', isOnline: true },
    ],
  },
  {
    id: 'room_4',
    name: 'Priya Patel',
    type: 'direct',
    lastMessage: 'Chart pattern is looking bullish for HDFC',
    lastMessageTime: new Date(now - h(8)).toISOString(),
    lastMessageSender: 'Priya Patel',
    unreadCount: 2,
    participants: [
      { userId: 'user_3', userName: 'Priya Patel', isOnline: true },
    ],
  },
  {
    id: 'room_5',
    name: 'Mutual Fund Investors',
    type: 'group',
    topic: 'MF portfolio discussion and reviews',
    lastMessage: 'Parag Parikh Flexi Cap is still the best',
    lastMessageTime: new Date(now - h(24)).toISOString(),
    lastMessageSender: 'Neha Singh',
    unreadCount: 0,
    participants: [
      { userId: 'user_2', userName: 'Arun Kumar', isOnline: true },
      { userId: 'user_4', userName: 'Neha Singh', isOnline: false },
      { userId: 'user_6', userName: 'Sneha Kapoor', isOnline: true },
    ],
  },
  {
    id: 'room_6',
    name: 'Vikram Reddy',
    type: 'direct',
    lastMessage: 'Thanks for the tip on SBIN!',
    lastMessageTime: new Date(now - h(48)).toISOString(),
    lastMessageSender: 'Vikram Reddy',
    unreadCount: 0,
    participants: [
      { userId: 'user_5', userName: 'Vikram Reddy', isOnline: true },
    ],
  },
];

export const mockChatMessages: Record<string, ChatMessage[]> = {
  room_1: [
    {
      id: 'msg_1_1',
      roomId: 'room_1',
      userId: 'user_2',
      userName: 'Arun Kumar',
      content: 'Good morning everyone! Nifty futures gap up opening expected today.',
      timestamp: new Date(now - h(3)).toISOString(),
      type: 'text',
      read: true,
    },
    {
      id: 'msg_1_2',
      roomId: 'room_1',
      userId: 'user_3',
      userName: 'Priya Patel',
      content: 'Yes, tracking 23500 as immediate resistance on the upside.',
      timestamp: new Date(now - h(2.5)).toISOString(),
      type: 'text',
      read: true,
    },
    {
      id: 'msg_1_3',
      roomId: 'room_1',
      userId: 'user_5',
      userName: 'Vikram Reddy',
      content: 'Bank Nifty also looking strong. HDFC Bank results were solid.',
      timestamp: new Date(now - h(2)).toISOString(),
      type: 'text',
      read: true,
    },
    {
      id: 'msg_1_4',
      roomId: 'room_1',
      userId: 'user_1',
      userName: 'Rahul Sharma',
      content: 'I am holding RELIANCE calls, targeting 2950 this week.',
      timestamp: new Date(now - h(1.5)).toISOString(),
      type: 'trade',
      read: true,
    },
    {
      id: 'msg_1_5',
      roomId: 'room_1',
      userId: 'user_2',
      userName: 'Arun Kumar',
      content: 'Nifty support at 23400, watch for bounce before going long.',
      timestamp: new Date(now - h(0.5)).toISOString(),
      type: 'text',
      read: false,
    },
  ],
  room_2: [
    {
      id: 'msg_2_1',
      roomId: 'room_2',
      userId: 'user_6',
      userName: 'Sneha Kapoor',
      content: 'Anyone following Reliance news? Retail expansion plans look promising.',
      timestamp: new Date(now - h(5)).toISOString(),
      type: 'text',
      read: true,
    },
    {
      id: 'msg_2_2',
      roomId: 'room_2',
      userId: 'user_2',
      userName: 'Arun Kumar',
      content: 'Yes, Jio Q4 subscriber additions were strong too. Bullish overall.',
      timestamp: new Date(now - h(4)).toISOString(),
      type: 'text',
      read: true,
    },
    {
      id: 'msg_2_3',
      roomId: 'room_2',
      userId: 'user_1',
      userName: 'Rahul Sharma',
      content: 'Q4 results next week, expectations?',
      timestamp: new Date(now - h(2)).toISOString(),
      type: 'text',
      read: true,
    },
  ],
  room_3: [
    {
      id: 'msg_3_1',
      roomId: 'room_3',
      userId: 'user_5',
      userName: 'Vikram Reddy',
      content: 'Iron condor on Nifty works best in range-bound markets. Setting up one for this week expiry.',
      timestamp: new Date(now - h(5)).toISOString(),
      type: 'text',
      read: false,
    },
  ],
  room_4: [
    {
      id: 'msg_4_1',
      roomId: 'room_4',
      userId: 'user_3',
      userName: 'Priya Patel',
      content: 'Hey! Checked that HDFC chart you recommended.',
      timestamp: new Date(now - h(10)).toISOString(),
      type: 'text',
      read: true,
    },
    {
      id: 'msg_4_2',
      roomId: 'room_4',
      userId: 'user_1',
      userName: 'Rahul Sharma',
      content: 'What did you think? The breakout above 1680 looked clean.',
      timestamp: new Date(now - h(9)).toISOString(),
      type: 'text',
      read: true,
    },
    {
      id: 'msg_4_3',
      roomId: 'room_4',
      userId: 'user_3',
      userName: 'Priya Patel',
      content: 'Chart pattern is looking bullish for HDFC. Entering at current levels.',
      timestamp: new Date(now - h(8)).toISOString(),
      type: 'text',
      read: false,
    },
  ],
  room_5: [
    {
      id: 'msg_5_1',
      roomId: 'room_5',
      userId: 'user_4',
      userName: 'Neha Singh',
      content: 'My SIP portfolio is up 18% this year. Parag Parikh Flexi Cap is still the best.',
      timestamp: new Date(now - h(24)).toISOString(),
      type: 'text',
      read: true,
    },
  ],
  room_6: [
    {
      id: 'msg_6_1',
      roomId: 'room_6',
      userId: 'user_5',
      userName: 'Vikram Reddy',
      content: 'Thanks for the tip on SBIN! Made a nice profit on that trade.',
      timestamp: new Date(now - h(48)).toISOString(),
      type: 'text',
      read: true,
    },
  ],
};
// ============ IPO Calendar ============
function daysFromNow(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
}

export const mockIPOs: IPOItem[] = [
  {
    id: 'ipo_1',
    companyName: 'LG Electronics India',
    logo: 'LG',
    sector: 'Consumer Electronics',
    openDate: daysFromNow(-2),
    closeDate: daysFromNow(2),
    listingDate: daysFromNow(7),
    priceBand: { min: 450, max: 475 },
    lotSize: 30,
    minInvestment: 14250,
    issueSize: 15000,
    freshIssue: 8000,
    offerForSale: 7000,
    totalShares: 32000000,
    totalBids: 2450000,
    totalBidAmount: 115000,
    subscriptionStatus: 'open',
    subscriptionQIB: 4.5,
    subscriptionHNI: 8.2,
    subscriptionRetail: 3.1,
    subscriptionTotal: 5.8,
    gmp: 85,
    gmpPercent: 18.5,
    expectedListingPrice: 552,
    expectedListingGain: 17.9,
    leadManagers: ['Kotak Mahindra Capital', 'Morgan Stanley India', 'J.P. Morgan India'],
    registrar: 'Link Intime India',
    rating: 4,
    revenue: 89500,
    netProfit: 10500,
    peRatio: 35.2,
    roe: 18.5,
    about: 'LG Electronics India is the Indian subsidiary of the South Korean conglomerate LG Electronics. The company is the market leader in the Indian consumer durables space with dominant market share across ACs (25%), refrigerators (22%), washing machines (20%) and TVs (18%).',
    strengths: ['Market leader in consumer durables', 'Strong brand recall and distribution network', 'Consistent revenue and profit growth', 'High ROE of 18.5%'],
    risks: ['Intense competition from Samsung, Panasonic', 'Dependence on imported components', 'Raw material price volatility'],
    applications: 1850000,
    sharesApplied: 96000000,
    allotmentDate: daysFromNow(5),
    isBookmarked: true,
  },
  {
    id: 'ipo_2',
    companyName: 'OYO Rooms',
    logo: 'OY',
    sector: 'Hospitality & Travel',
    openDate: daysFromNow(5),
    closeDate: daysFromNow(9),
    listingDate: daysFromNow(14),
    priceBand: { min: 270, max: 290 },
    lotSize: 50,
    minInvestment: 14500,
    issueSize: 8430,
    freshIssue: 5430,
    offerForSale: 3000,
    totalShares: 30000000,
    totalBids: 0,
    totalBidAmount: 0,
    subscriptionStatus: 'upcoming',
    subscriptionQIB: 0,
    subscriptionHNI: 0,
    subscriptionRetail: 0,
    subscriptionTotal: 0,
    gmp: 35,
    gmpPercent: 12.5,
    expectedListingPrice: 320,
    expectedListingGain: 11.2,
    leadManagers: ['ICICI Securities', 'Nomura', 'Citi'],
    registrar: 'KFin Technologies',
    rating: 3,
    revenue: 12450,
    netProfit: -1230,
    peRatio: 0,
    roe: -5.2,
    about: 'OYO Rooms is India\'s largest hospitality chain operating budget hotels and homes. The company has a presence in over 35 countries with 157,000+ rooms. The IPO is a mix of fresh issue and offer for sale by existing investors including SoftBank.',
    strengths: ['Largest budget hotel network in India', 'Technology-driven operations', 'Asset-light business model', 'Strong brand in travel segment'],
    risks: ['Not yet profitable', 'High competition from OYO, Treebo', 'Regulatory challenges in international markets', 'Post-COVID recovery uncertain'],
    applications: 0,
    sharesApplied: 0,
    isBookmarked: false,
  },
  {
    id: 'ipo_3',
    companyName: 'Vishal Mega Mart',
    logo: 'VM',
    sector: 'Retail',
    openDate: daysFromNow(-5),
    closeDate: daysFromNow(-1),
    listingDate: daysFromNow(3),
    priceBand: { min: 340, max: 360 },
    lotSize: 40,
    minInvestment: 14400,
    issueSize: 8500,
    freshIssue: 3500,
    offerForSale: 5000,
    totalShares: 24000000,
    totalBids: 3800000,
    totalBidAmount: 132000,
    subscriptionStatus: 'closed',
    subscriptionQIB: 6.2,
    subscriptionHNI: 12.5,
    subscriptionRetail: 4.8,
    subscriptionTotal: 7.5,
    gmp: 72,
    gmpPercent: 20.5,
    expectedListingPrice: 432,
    expectedListingGain: 20.0,
    leadManagers: ['DAM Capital', 'IIFL Securities', 'SBI Capital Markets'],
    registrar: 'Link Intime India',
    rating: 4,
    revenue: 28500,
    netProfit: 2100,
    peRatio: 42.3,
    roe: 15.8,
    about: 'Vishal Mega Mart is a leading retail chain focused on value fashion and general merchandise. With 650+ stores across 400+ cities in India, the company targets the mass-market segment with affordable pricing.',
    strengths: ['Strong presence in tier 2/3 cities', 'Value-focused retail model', 'High store-level profitability', 'Experienced management team'],
    risks: ['High competition from DMart, Reliance Retail', 'Real estate cost inflation', 'Supply chain disruptions'],
    applications: 3200000,
    sharesApplied: 90000000,
    allotmentDate: daysFromNow(0),
    listingPrice: 432,
    listingGain: 20.0,
    isBookmarked: true,
  },
  {
    id: 'ipo_4',
    companyName: 'Swiggy',
    logo: 'SW',
    sector: 'Food Tech',
    openDate: daysFromNow(12),
    closeDate: daysFromNow(16),
    listingDate: daysFromNow(21),
    priceBand: { min: 380, max: 410 },
    lotSize: 35,
    minInvestment: 14350,
    issueSize: 12000,
    freshIssue: 5000,
    offerForSale: 7000,
    totalShares: 30000000,
    totalBids: 0,
    totalBidAmount: 0,
    subscriptionStatus: 'upcoming',
    subscriptionQIB: 0,
    subscriptionHNI: 0,
    subscriptionRetail: 0,
    subscriptionTotal: 0,
    gmp: 45,
    gmpPercent: 11.5,
    expectedListingPrice: 452,
    expectedListingGain: 10.8,
    leadManagers: ['Kotak Mahindra Capital', 'Goldman Sachs', 'Citi'],
    registrar: 'KFin Technologies',
    rating: 3,
    revenue: 18500,
    netProfit: -850,
    peRatio: 0,
    roe: -3.8,
    about: 'Swiggy is India\'s leading food delivery and quick commerce platform. The company operates across 500+ cities with 250,000+ restaurant partners and has expanded into instant grocery delivery through Instamart.',
    strengths: ['Market leader in food delivery', 'Strong Instamart quick commerce growth', 'Large delivery partner network', 'Technology-first approach'],
    risks: ['Heavy losses despite revenue growth', 'Intense competition from Zomato, Zepto', 'Regulatory risks around gig economy', 'High cash burn rate'],
    applications: 0,
    sharesApplied: 0,
    isBookmarked: false,
  },
  {
    id: 'ipo_5',
    companyName: 'NTPC Green Energy',
    logo: 'NG',
    sector: 'Renewable Energy',
    openDate: daysFromNow(-10),
    closeDate: daysFromNow(-6),
    listingDate: daysFromNow(-3),
    priceBand: { min: 108, max: 115 },
    lotSize: 125,
    minInvestment: 14375,
    issueSize: 10000,
    freshIssue: 10000,
    offerForSale: 0,
    totalShares: 89000000,
    totalBids: 5200000,
    totalBidAmount: 59000,
    subscriptionStatus: 'listed',
    subscriptionQIB: 8.5,
    subscriptionHNI: 15.2,
    subscriptionRetail: 6.8,
    subscriptionTotal: 9.8,
    gmp: 25,
    gmpPercent: 22.0,
    expectedListingPrice: 140,
    expectedListingGain: 21.7,
    leadManagers: ['IDBI Capital', 'YES Securities', 'BOB Capital Markets'],
    registrar: 'Link Intime India',
    rating: 4,
    revenue: 5600,
    netProfit: 1450,
    peRatio: 28.5,
    roe: 12.2,
    about: 'NTPC Green Energy is the renewable energy arm of NTPC Ltd, India\'s largest power utility. The company focuses on solar and wind power generation with a target to achieve 60 GW of renewable capacity by 2032.',
    strengths: ['Backed by NTPC (government PSU)', 'Strong renewable energy pipeline', 'Stable cash flows from PPAs', 'Government support for green energy'],
    risks: ['Regulatory changes in renewable sector', 'Land acquisition challenges', 'Dependence on solar panel imports'],
    applications: 4800000,
    sharesApplied: 850000000,
    allotmentDate: daysFromNow(-8),
    listingPrice: 138,
    listingGain: 20.0,
    isBookmarked: false,
  },
  {
    id: 'ipo_6',
    companyName: 'Ather Energy',
    logo: 'AE',
    sector: 'Electric Vehicles',
    openDate: daysFromNow(18),
    closeDate: daysFromNow(22),
    listingDate: daysFromNow(28),
    priceBand: { min: 420, max: 450 },
    lotSize: 32,
    minInvestment: 14400,
    issueSize: 7500,
    freshIssue: 4500,
    offerForSale: 3000,
    totalShares: 17500000,
    totalBids: 0,
    totalBidAmount: 0,
    subscriptionStatus: 'upcoming',
    subscriptionQIB: 0,
    subscriptionHNI: 0,
    subscriptionRetail: 0,
    subscriptionTotal: 0,
    gmp: 60,
    gmpPercent: 13.8,
    expectedListingPrice: 505,
    expectedListingGain: 12.5,
    leadManagers: ['ICICI Securities', 'HSBC Securities', 'DAM Capital'],
    registrar: 'Link Intime India',
    rating: 4,
    revenue: 3200,
    netProfit: -420,
    peRatio: 0,
    roe: -6.5,
    about: 'Ather Energy is a leading Indian electric two-wheeler manufacturer known for its premium electric scooters. The company has a 15% market share in the EV two-wheeler segment and operates 1,500+ fast-charging grid points across India.',
    strengths: ['Premium brand in EV space', 'Strong R&D and technology', 'Fast-growing charging network', 'High customer satisfaction'],
    risks: ['Not yet profitable', 'Battery cost volatility', 'Government subsidy dependence', 'Competition from Ola Electric, Bajaj'],
    applications: 0,
    sharesApplied: 0,
    isBookmarked: false,
  },
];

// ============ Economic Calendar ============
function dateStr(daysOffset: number): string {
  const d = new Date();
  d.setDate(d.getDate() + daysOffset);
  return d.toISOString().split('T')[0];
}

export const mockEconomicEvents: EconomicEvent[] = [
  {
    id: 'econ_1',
    title: 'RBI Monetary Policy Decision',
    description: 'The Reserve Bank of India announces its bi-monthly monetary policy decision including the repo rate, reverse repo rate, and CRR.',
    date: dateStr(-5),
    time: '10:00 AM',
    timezone: 'IST',
    category: 'central_bank',
    country: 'India',
    countryCode: 'IN',
    importance: 'high',
    previous: '6.50%',
    forecast: '6.25%',
    actual: '6.25%',
    isCompleted: true,
    impact: 'positive',
    affectedAssets: ['NIFTY', 'BANKNIFTY', 'INR', 'G-Secs'],
    source: 'RBI',
    notes: 'RBI cut repo rate by 25 bps for the first time in 5 years. Markets rallied 1.5% post announcement.'
  },
  {
    id: 'econ_2',
    title: 'India GDP Growth Rate (Q4 FY26)',
    description: 'Quarterly Gross Domestic Product data for India, measuring the value of all goods and services produced.',
    date: dateStr(-3),
    time: '5:30 PM',
    timezone: 'IST',
    category: 'gdp',
    country: 'India',
    countryCode: 'IN',
    importance: 'high',
    previous: '7.2%',
    forecast: '6.8%',
    actual: '7.1%',
    isCompleted: true,
    impact: 'positive',
    affectedAssets: ['NIFTY', 'SENSEX', 'INR'],
    source: 'MOSPI',
  },
  {
    id: 'econ_3',
    title: 'US Federal Reserve Interest Rate Decision',
    description: 'Federal Open Market Committee (FOMC) announces its decision on the federal funds rate target.',
    date: dateStr(-2),
    time: '2:00 PM',
    timezone: 'ET',
    category: 'central_bank',
    country: 'United States',
    countryCode: 'US',
    importance: 'high',
    previous: '5.50%',
    forecast: '5.50%',
    actual: '5.50%',
    isCompleted: true,
    impact: 'neutral',
    affectedAssets: ['S&P 500', 'NASDAQ', 'DXY', 'Gold', 'INR'],
    source: 'Federal Reserve',
  },
  {
    id: 'econ_4',
    title: 'India CPI Inflation Data (May)',
    description: 'Consumer Price Index data released by the Ministry of Statistics, measuring retail inflation across urban and rural India.',
    date: dateStr(0),
    time: '5:30 PM',
    timezone: 'IST',
    category: 'inflation',
    country: 'India',
    countryCode: 'IN',
    importance: 'high',
    previous: '4.85%',
    forecast: '4.60%',
    isCompleted: false,
    impact: 'unknown',
    affectedAssets: ['NIFTY', 'BANKNIFTY', 'INR', 'G-Secs'],
    source: 'MOSPI',
  },
  {
    id: 'econ_5',
    title: 'India IIP Data (April)',
    description: 'Index of Industrial Production measuring growth in industrial output across mining, manufacturing, and electricity sectors.',
    date: dateStr(1),
    time: '5:30 PM',
    timezone: 'IST',
    category: 'industry',
    country: 'India',
    countryCode: 'IN',
    importance: 'medium',
    previous: '4.2%',
    forecast: '5.0%',
    isCompleted: false,
    impact: 'unknown',
    affectedAssets: ['NIFTY', 'SENSEX'],
    source: 'MOSPI',
  },
  {
    id: 'econ_6',
    title: 'US Non-Farm Payrolls (May)',
    description: 'Monthly employment data showing the change in the number of employed people in the US excluding farm workers and certain other categories.',
    date: dateStr(2),
    time: '8:30 AM',
    timezone: 'ET',
    category: 'employment',
    country: 'United States',
    countryCode: 'US',
    importance: 'high',
    previous: '175K',
    forecast: '190K',
    isCompleted: false,
    impact: 'unknown',
    affectedAssets: ['S&P 500', 'DXY', 'Gold', 'INR'],
    source: 'Bureau of Labor Statistics',
  },
  {
    id: 'econ_7',
    title: 'India Trade Balance (May)',
    description: 'Monthly trade data showing the difference between India\'s exports and imports, a key indicator for the external sector.',
    date: dateStr(3),
    time: '6:00 PM',
    timezone: 'IST',
    category: 'trade',
    country: 'India',
    countryCode: 'IN',
    importance: 'medium',
    previous: '-$18.5B',
    forecast: '-$17.2B',
    isCompleted: false,
    impact: 'unknown',
    affectedAssets: ['INR', 'IT Stocks'],
    source: 'Ministry of Commerce',
  },
  {
    id: 'econ_8',
    title: 'India Union Budget Presentation',
    description: 'Government of India presents the annual Union Budget outlining fiscal policy, taxation changes, and expenditure for the coming financial year.',
    date: dateStr(30),
    time: '11:00 AM',
    timezone: 'IST',
    category: 'fiscal',
    country: 'India',
    countryCode: 'IN',
    importance: 'high',
    previous: '₹48.21L Cr',
    forecast: '₹52.00L Cr',
    isCompleted: false,
    impact: 'unknown',
    affectedAssets: ['NIFTY', 'SENSEX', 'INR', 'G-Secs'],
    source: 'Ministry of Finance',
  },
  {
    id: 'econ_9',
    title: 'India Manufacturing PMI (May)',
    description: 'HSBC Manufacturing Purchasing Managers\' Index measuring health of the manufacturing sector based on survey of 400+ manufacturers.',
    date: dateStr(0),
    time: '10:30 AM',
    timezone: 'IST',
    category: 'industry',
    country: 'India',
    countryCode: 'IN',
    importance: 'medium',
    previous: '58.8',
    forecast: '59.2',
    isCompleted: false,
    impact: 'unknown',
    affectedAssets: ['NIFTY', 'SENSEX'],
    source: 'HSBC',
  },
  {
    id: 'econ_10',
    title: 'India Services PMI (May)',
    description: 'HSBC Services PMI tracking business conditions in the Indian services sector.',
    date: dateStr(1),
    time: '10:30 AM',
    timezone: 'IST',
    category: 'industry',
    country: 'India',
    countryCode: 'IN',
    importance: 'medium',
    previous: '60.2',
    forecast: '60.5',
    isCompleted: false,
    impact: 'unknown',
    affectedAssets: ['NIFTY'],
    source: 'HSBC',
  },
  {
    id: 'econ_11',
    title: 'India Unemployment Rate (May)',
    description: 'Monthly unemployment rate data from the Centre for Monitoring Indian Economy (CMIE).',
    date: dateStr(5),
    time: '5:00 PM',
    timezone: 'IST',
    category: 'employment',
    country: 'India',
    countryCode: 'IN',
    importance: 'medium',
    previous: '7.6%',
    forecast: '7.4%',
    isCompleted: false,
    impact: 'unknown',
    affectedAssets: ['NIFTY', 'Consumer Stocks'],
    source: 'CMIE',
  },
  {
    id: 'econ_12',
    title: 'ECB Interest Rate Decision',
    description: 'European Central Bank announces interest rate decision for the Eurozone.',
    date: dateStr(6),
    time: '1:15 PM',
    timezone: 'CET',
    category: 'central_bank',
    country: 'Eurozone',
    countryCode: 'EU',
    importance: 'high',
    previous: '4.25%',
    forecast: '4.00%',
    isCompleted: false,
    impact: 'unknown',
    affectedAssets: ['EUR/USD', 'S&P 500', 'Gold', 'INR'],
    source: 'ECB',
  },
  {
    id: 'econ_13',
    title: 'India WPI Inflation (May)',
    description: 'Wholesale Price Index data measuring inflation at the wholesale level.',
    date: dateStr(7),
    time: '12:00 PM',
    timezone: 'IST',
    category: 'inflation',
    country: 'India',
    countryCode: 'IN',
    importance: 'low',
    previous: '2.45%',
    forecast: '2.60%',
    isCompleted: false,
    impact: 'unknown',
    affectedAssets: ['INR', 'G-Secs'],
    source: 'Ministry of Commerce',
  },
  {
    id: 'econ_14',
    title: 'India Steel Production (May)',
    description: 'Monthly steel production data from Joint Plant Committee, a key indicator of industrial activity.',
    date: dateStr(4),
    time: '4:00 PM',
    timezone: 'IST',
    category: 'industry',
    country: 'India',
    countryCode: 'IN',
    importance: 'low',
    previous: '12.4 MT',
    forecast: '12.8 MT',
    isCompleted: false,
    impact: 'unknown',
    affectedAssets: ['TATASTEEL', 'JSWSTEEL'],
    source: 'JPC',
  },
];

// ============ Earnings Call Summaries ============

const mockEarningsQuarters: Record<string, EarningsQuarter[]> = {
  RELIANCE: [
    { quarter: 'Q1 FY25', date: '2024-07-15', revenue: 178900, netProfit: 16500, eps: 24.4, margin: 9.2 },
    { quarter: 'Q2 FY25', date: '2024-10-14', revenue: 192300, netProfit: 18200, eps: 26.9, margin: 9.5 },
    { quarter: 'Q3 FY25', date: '2025-01-17', revenue: 205600, netProfit: 19500, eps: 28.8, margin: 9.5 },
    { quarter: 'Q4 FY25', date: '2025-04-15', revenue: 223500, netProfit: 21345, eps: 31.5, margin: 9.6 },
  ],
  HDFCBANK: [
    { quarter: 'Q1 FY25', date: '2024-07-20', revenue: 76500, netProfit: 16200, eps: 21.5, margin: 21.2 },
    { quarter: 'Q2 FY25', date: '2024-10-19', revenue: 80200, netProfit: 17100, eps: 22.7, margin: 21.3 },
    { quarter: 'Q3 FY25', date: '2025-01-16', revenue: 83500, netProfit: 17900, eps: 23.8, margin: 21.4 },
    { quarter: 'Q4 FY25', date: '2025-04-18', revenue: 87200, netProfit: 18650, eps: 24.8, margin: 21.4 },
  ],
  TCS: [
    { quarter: 'Q1 FY25', date: '2024-07-11', revenue: 62000, netProfit: 12500, eps: 34.1, margin: 20.2 },
    { quarter: 'Q2 FY25', date: '2024-10-10', revenue: 64200, netProfit: 13000, eps: 35.5, margin: 20.3 },
    { quarter: 'Q3 FY25', date: '2025-01-09', revenue: 65800, netProfit: 13350, eps: 36.4, margin: 20.3 },
    { quarter: 'Q4 FY25', date: '2025-04-11', revenue: 67100, netProfit: 13500, eps: 36.8, margin: 20.1 },
  ],
  INFY: [
    { quarter: 'Q1 FY25', date: '2024-07-18', revenue: 39500, netProfit: 8200, eps: 19.7, margin: 20.8 },
    { quarter: 'Q2 FY25', date: '2024-10-17', revenue: 41100, netProfit: 8600, eps: 20.7, margin: 20.9 },
    { quarter: 'Q3 FY25', date: '2025-01-16', revenue: 42300, netProfit: 8850, eps: 21.3, margin: 20.9 },
    { quarter: 'Q4 FY25', date: '2025-04-17', revenue: 43100, netProfit: 8900, eps: 21.4, margin: 20.6 },
  ],
  ICICIBANK: [
    { quarter: 'Q1 FY25', date: '2024-07-27', revenue: 44500, netProfit: 11200, eps: 15.8, margin: 25.2 },
    { quarter: 'Q2 FY25', date: '2024-10-26', revenue: 46800, netProfit: 11900, eps: 16.8, margin: 25.4 },
    { quarter: 'Q3 FY25', date: '2025-01-25', revenue: 48200, netProfit: 12400, eps: 17.5, margin: 25.7 },
    { quarter: 'Q4 FY25', date: '2025-04-25', revenue: 49800, netProfit: 12800, eps: 18.1, margin: 25.7 },
  ],
  SBIN: [
    { quarter: 'Q1 FY25', date: '2024-08-03', revenue: 89500, netProfit: 18500, eps: 20.7, margin: 20.7 },
    { quarter: 'Q2 FY25', date: '2024-11-02', revenue: 93200, netProfit: 19400, eps: 21.7, margin: 20.8 },
    { quarter: 'Q3 FY25', date: '2025-02-01', revenue: 95800, netProfit: 20100, eps: 22.5, margin: 21.0 },
    { quarter: 'Q4 FY25', date: '2025-05-09', revenue: 98500, netProfit: 20600, eps: 23.1, margin: 20.9 },
  ],
};

export const mockEarningsData: EarningsSummary[] = [
  {
    id: 'earnings_RELIANCE_2026-04-15',
    symbol: 'RELIANCE',
    companyName: 'Reliance Industries Ltd.',
    quarter: 'Q4 FY26',
    fiscalYear: 'FY26',
    date: '2026-04-15',
    metrics: {
      revenue: 241000, revenueGrowth: 7.8,
      netProfit: 21345, profitGrowth: 12.1,
      eps: 31.5, epsGrowth: 12.1,
      operatingMargin: 12.8, netMargin: 8.9,
      revenueBeat: 2.3, profitBeat: 4.8,
      ebitda: 48500, ebitdaMargin: 20.1,
    },
    peerComparison: [
      { symbol: 'RELIANCE', name: 'Reliance Industries', revenue: 241000, profit: 21345, peRatio: 28.5, revenueGrowth: 7.8, profitGrowth: 12.1 },
      { symbol: 'TCS', name: 'Tata Consultancy Services', revenue: 67100, profit: 13500, peRatio: 35.2, revenueGrowth: 5.2, profitGrowth: 4.3 },
      { symbol: 'HDFCBANK', name: 'HDFC Bank', revenue: 87200, profit: 18650, peRatio: 18.9, revenueGrowth: 14.2, profitGrowth: 15.1 },
      { symbol: 'INFY', name: 'Infosys', revenue: 43100, profit: 8900, peRatio: 28.1, revenueGrowth: 4.6, profitGrowth: 3.8 },
    ],
    historicalQuarters: mockEarningsQuarters.RELIANCE,
    managementHighlights: [
      'Jio added 11M new subscribers, reaching 490M total',
      'Retail segment revenue grew 18% YoY, store count at 18,500',
      'O2C margins improved 50 bps despite weaker refining',
      'New Energy business: 5GW renewable capacity operational',
      'Dividend declared at Rs 10 per share',
    ],
    growthDrivers: [
      'Jio 5G subscriber conversion driving ARPU growth',
      'Retail expansion into tier 2/3 cities',
      'New Energy vertical gaining momentum',
      'Digital services ecosystem (JioMart, JioPay)',
    ],
    riskFactors: [
      'Global refining margin volatility',
      'Regulatory changes in telecom sector',
      'High capex intensity across businesses',
      'Competition from new-age digital platforms',
    ],
    analystConsensus: 'buy',
    analystTargetPrice: 3450,
    analystTargetLow: 2900,
    analystTargetHigh: 3800,
    executiveSummary: 'Reliance Industries reported revenue of Rs 2,41,000 Cr for the quarter, which rose 7.8% YoY. Net profit rose 12.1% YoY to Rs 21,345 Cr, with EPS of Rs 31.50. Operating margins stood at 12.8% and net margins at 8.9%. EBITDA came in at Rs 48,500 Cr with an EBITDA margin of 20.1%. The company beat estimates on both revenue and profit.',
    keyTakeaways: [
      'Revenue growth of 7.8% driven by retail (+18%) and Jio subscriber additions',
      'Operating margin expansion across all segments except O2C',
      'Strong cash flow generation with Rs 48,500 Cr EBITDA',
      'Jio 5G network now covers 95% of urban India',
      'Retail EBITDA margin improved to 8.2% from 7.5%',
    ],
    sentimentScore: 55,
    sentimentLabel: 'bullish',
    confidence: 82,
    marketReaction: { preMarketChange: 1.8, dayChange: 2.3, volumeSurge: 45 },
    source: 'Toroloom AI Analysis',
  },
  {
    id: 'earnings_HDFCBANK_2026-04-18',
    symbol: 'HDFCBANK',
    companyName: 'HDFC Bank Ltd.',
    quarter: 'Q4 FY26',
    fiscalYear: 'FY26',
    date: '2026-04-18',
    metrics: {
      revenue: 87200, revenueGrowth: 14.2,
      netProfit: 18650, profitGrowth: 15.1,
      eps: 24.8, epsGrowth: 15.1,
      operatingMargin: 28.5, netMargin: 21.4,
      revenueBeat: 3.1, profitBeat: 5.2,
      ebitda: 31000, ebitdaMargin: 35.6,
    },
    peerComparison: [
      { symbol: 'HDFCBANK', name: 'HDFC Bank', revenue: 87200, profit: 18650, peRatio: 18.9, revenueGrowth: 14.2, profitGrowth: 15.1 },
      { symbol: 'ICICIBANK', name: 'ICICI Bank', revenue: 49800, profit: 12800, peRatio: 16.5, revenueGrowth: 12.4, profitGrowth: 16.2 },
      { symbol: 'SBIN', name: 'SBI', revenue: 98500, profit: 20600, peRatio: 10.2, revenueGrowth: 10.1, profitGrowth: 11.4 },
      { symbol: 'RELIANCE', name: 'Reliance Industries', revenue: 241000, profit: 21345, peRatio: 28.5, revenueGrowth: 7.8, profitGrowth: 12.1 },
    ],
    historicalQuarters: mockEarningsQuarters.HDFCBANK,
    managementHighlights: [
      'NII grew 15.5% YoY driven by loan growth of 18%',
      'Asset quality improves: GNPA at 1.2% vs 1.4% QoQ',
      'CASA ratio stable at 38%, NIM at 3.5%',
      'Digital transactions up 35% YoY',
      'Merger synergies fully realized, cost saves of Rs 3,500 Cr',
    ],
    growthDrivers: [
      'Merger synergies with HDFC Ltd',
      'Retail loan growth in housing and auto segments',
      'Expansion in unsecured lending with risk controls',
      'Digital banking platform adoption',
    ],
    riskFactors: [
      'NIM compression due to rising deposit costs',
      'Regulatory scrutiny on unsecured lending',
      'Competition from fintech lenders',
      'Macroeconomic slowdown impacting credit growth',
    ],
    analystConsensus: 'strong_buy',
    analystTargetPrice: 2100,
    analystTargetLow: 1750,
    analystTargetHigh: 2350,
    executiveSummary: 'HDFC Bank reported revenue of Rs 87,200 Cr for the quarter, which rose 14.2% YoY. Net profit rose 15.1% YoY to Rs 18,650 Cr, with EPS of Rs 24.80. Operating margins stood at 28.5% and net margins at 21.4%. EBITDA came in at Rs 31,000 Cr with an EBITDA margin of 35.6%. The company beat estimates on both revenue and profit.',
    keyTakeaways: [
      'Strong loan growth of 18% YoY with stable NIMs',
      'Asset quality at record low GNPA of 1.2%',
      'Highest-ever quarterly profit at Rs 18,650 Cr',
      'Merger cost synergies of Rs 3,500 Cr achieved ahead of schedule',
      'Return on Assets (RoA) improved to 2.1%',
    ],
    sentimentScore: 72,
    sentimentLabel: 'bullish',
    confidence: 88,
    marketReaction: { preMarketChange: 2.5, dayChange: 4.1, volumeSurge: 85 },
    source: 'Toroloom AI Analysis',
  },
  {
    id: 'earnings_TCS_2026-04-11',
    symbol: 'TCS',
    companyName: 'Tata Consultancy Services',
    quarter: 'Q4 FY26',
    fiscalYear: 'FY26',
    date: '2026-04-11',
    metrics: {
      revenue: 67100, revenueGrowth: 5.2,
      netProfit: 13500, profitGrowth: 4.3,
      eps: 36.8, epsGrowth: 4.3,
      operatingMargin: 25.8, netMargin: 20.1,
      revenueBeat: -1.2, profitBeat: 0.8,
      ebitda: 18750, ebitdaMargin: 27.9,
    },
    historicalQuarters: mockEarningsQuarters.TCS,
    peerComparison: [
      { symbol: 'TCS', name: 'Tata Consultancy Services', revenue: 67100, profit: 13500, peRatio: 35.2, revenueGrowth: 5.2, profitGrowth: 4.3 },
      { symbol: 'INFY', name: 'Infosys', revenue: 43100, profit: 8900, peRatio: 28.1, revenueGrowth: 4.6, profitGrowth: 3.8 },
      { symbol: 'WIPRO', name: 'Wipro', revenue: 22100, profit: 3200, peRatio: 24.3, revenueGrowth: 2.1, profitGrowth: -1.5 },
    ],
    managementHighlights: [
      'Won 12 large deals worth $8.7B in the quarter',
      'BFSI vertical growth at 8.5% YoY',
      'Headcount addition of 8,500 (net)',
      'Attrition rate stable at 12.3%',
      'Declared dividend of Rs 28 per share',
    ],
    growthDrivers: [
      'Cloud transformation deals in BFSI sector',
      'AI/GenAI services pipeline growing 45% QoQ',
      'Strong deal pipeline at $12.5B',
      'Geographic diversification into Europe & APAC',
    ],
    riskFactors: [
      'Visa policy changes in US impacting onsite mix',
      'Wage cost inflation impacting margins',
      'Discretionary spending slowdown in US market',
      'Currency appreciation risk against USD',
    ],
    analystConsensus: 'hold',
    analystTargetPrice: 4200,
    analystTargetLow: 3600,
    analystTargetHigh: 4700,
    executiveSummary: 'Tata Consultancy Services reported revenue of Rs 67,100 Cr for the quarter, which rose 5.2% YoY. Net profit rose 4.3% YoY to Rs 13,500 Cr, with EPS of Rs 36.80. Operating margins stood at 25.8% and net margins at 20.1%. EBITDA came in at Rs 18,750 Cr with an EBITDA margin of 27.9%. Revenue slightly missed estimates while profit beat expectations.',
    keyTakeaways: [
      'Revenue growth of 5.2% — on the lower end of guidance',
      'Large deal TCV at $8.7B, up 12% YoY',
      'EBIT margin contracted 45 bps to 25.8% due to wage hikes',
      'AI/GenAI services pipeline growing rapidly at 45% QoQ',
      'Subdued BFSI discretionary spending remains a concern',
    ],
    sentimentScore: 10,
    sentimentLabel: 'neutral',
    confidence: 65,
    marketReaction: { preMarketChange: -0.5, dayChange: -1.2, volumeSurge: 30 },
    source: 'Toroloom AI Analysis',
  },
  {
    id: 'earnings_ICICIBANK_2026-04-25',
    symbol: 'ICICIBANK',
    companyName: 'ICICI Bank Ltd.',
    quarter: 'Q4 FY26',
    fiscalYear: 'FY26',
    date: '2026-04-25',
    metrics: {
      revenue: 49800, revenueGrowth: 12.4,
      netProfit: 12800, profitGrowth: 16.2,
      eps: 18.1, epsGrowth: 16.2,
      operatingMargin: 32.4, netMargin: 25.7,
      revenueBeat: 1.8, profitBeat: 3.5,
      ebitda: 20100, ebitdaMargin: 40.4,
    },
    historicalQuarters: mockEarningsQuarters.ICICIBANK,
    peerComparison: [
      { symbol: 'ICICIBANK', name: 'ICICI Bank', revenue: 49800, profit: 12800, peRatio: 16.5, revenueGrowth: 12.4, profitGrowth: 16.2 },
      { symbol: 'HDFCBANK', name: 'HDFC Bank', revenue: 87200, profit: 18650, peRatio: 18.9, revenueGrowth: 14.2, profitGrowth: 15.1 },
      { symbol: 'SBIN', name: 'SBI', revenue: 98500, profit: 20600, peRatio: 10.2, revenueGrowth: 10.1, profitGrowth: 11.4 },
    ],
    managementHighlights: [
      'Retail loan book grew 16% YoY',
      'Net Interest Margin stable at 4.3%',
      'GNPA improved to 1.8% from 2.0% QoQ',
      'Subsidiary ICICI Securities contributed Rs 850 Cr profit',
      'Digital platform iMobile now has 35M+ users',
    ],
    growthDrivers: [
      'Retail and SME loan growth accelerating',
      'Fee income growing at 18% YoY',
      'Improving asset quality driving lower provisions',
      'Digital banking cost efficiencies',
    ],
    riskFactors: [
      'Intense competition for deposits driving up costs',
      'Exposure to unsecured retail loans',
      'Regulatory changes in banking sector',
      'Geopolitical risks in overseas operations',
    ],
    analystConsensus: 'buy',
    analystTargetPrice: 1420,
    analystTargetLow: 1150,
    analystTargetHigh: 1600,
    executiveSummary: 'ICICI Bank reported revenue of Rs 49,800 Cr for the quarter, which rose 12.4% YoY. Net profit rose 16.2% YoY to Rs 12,800 Cr, with EPS of Rs 18.10. Operating margins stood at 32.4% and net margins at 25.7%. EBITDA came in at Rs 20,100 Cr with an EBITDA margin of 40.4%. The company beat estimates on both revenue and profit.',
    keyTakeaways: [
      'NII growth of 14.5% YoY driven by loan growth',
      'Asset quality improvement continues with GNPA at 1.8%',
      'Profit growth of 16.2% — best in the banking cohort',
      'Cost-to-income ratio improved to 40.2% from 42.5%',
      'Subsidiary performance (ICICI Securities, Life) strong',
    ],
    sentimentScore: 65,
    sentimentLabel: 'bullish',
    confidence: 85,
    marketReaction: { preMarketChange: 1.2, dayChange: 2.8, volumeSurge: 55 },
    source: 'Toroloom AI Analysis',
  },
];

// ============ Sentiment Analysis ============

/** Generate 30 days of sentiment data points with realistic variance */
function generateSentimentHistory(baseScore: number, symbol: string): SentimentDataPoint[] {
  const points: SentimentDataPoint[] = [];
  let score = baseScore;
  for (let i = 29; i >= 0; i--) {
    const date = new Date();
    date.setDate(date.getDate() - i);
    if (date.getDay() === 0 || date.getDay() === 6) continue; // Skip weekends

    const drift = (Math.random() - 0.48) * 8;
    score = Math.max(-100, Math.min(100, score + drift));
    const dailyScore = Math.round(score);

    points.push({
      date: date.toISOString().split('T')[0],
      overallScore: dailyScore,
      sourceBreakdown: {
        newsScore: Math.round(dailyScore + (Math.random() - 0.5) * 15),
        socialScore: Math.round(dailyScore + (Math.random() - 0.5) * 25),
        analystScore: Math.round(dailyScore + (Math.random() - 0.5) * 10),
        aiScore: Math.round(dailyScore + (Math.random() - 0.5) * 12),
      },
      articleCount: Math.floor(Math.random() * 8) + 2,
      mentionCount: Math.floor(Math.random() * 500) + 50,
    });
  }
  return points;
}

const sentimentArticles: SentimentArticle[] = [
  { id: 'sa1', title: 'RIL Q4 Results Beat Estimates — Retail, Jio Drive Growth', summary: 'Reliance Industries reported strong quarterly numbers with retail revenue up 18% and Jio adding 11M subscribers.', source: 'Economic Times', sentiment: 'positive', score: 75, publishedAt: new Date(Date.now() - 3600000).toISOString() },
  { id: 'sa2', title: 'Reliance Retail Expansion Accelerates — 500 New Stores Planned', summary: 'Reliance Retail plans to add 500 new stores in tier 2/3 cities, targeting 20% revenue growth.', source: 'Moneycontrol', sentiment: 'positive', score: 60, publishedAt: new Date(Date.now() - 7200000).toISOString() },
  { id: 'sa3', title: 'Oil Prices Drop — O2C Margins Under Pressure for RIL', summary: 'Global crude volatility impacts refining margins for Reliance O2C business in near term.', source: 'Reuters', sentiment: 'negative', score: -45, publishedAt: new Date(Date.now() - 10800000).toISOString() },
  { id: 'sa4', title: 'HDFC Bank NIM Stable at 3.5%, Loan Growth at 18%', summary: 'HDFC Bank maintains healthy net interest margins despite rising deposit costs. Asset quality improves.', source: 'CNBC TV18', sentiment: 'positive', score: 70, publishedAt: new Date(Date.now() - 1800000).toISOString() },
  { id: 'sa5', title: 'HDFC Bank Merger Synergies Fully Realized', summary: 'HDFC Ltd merger cost synergies of Rs 3,500 Cr achieved ahead of schedule — analysts positive.', source: 'Business Standard', sentiment: 'positive', score: 55, publishedAt: new Date(Date.now() - 5400000).toISOString() },
  { id: 'sa6', title: 'TCS Wins $2B Cloud Deal from European Bank', summary: 'Tata Consultancy Services signs multi-year cloud transformation deal worth $2 billion.', source: 'Financial Express', sentiment: 'positive', score: 65, publishedAt: new Date(Date.now() - 21600000).toISOString() },
  { id: 'sa7', title: 'IT Sector Faces Headwinds — US Spending Concerns Mount', summary: 'Reduced discretionary spending by US clients puts pressure on Indian IT firms in near term.', source: 'Bloomberg', sentiment: 'negative', score: -55, publishedAt: new Date(Date.now() - 43200000).toISOString() },
  { id: 'sa8', title: 'Infosys AI Pipeline Grows 45% QoQ — Strong Deal Wins', summary: 'Infosys AI/GenAI services pipeline growing rapidly with major deal wins in BFSI sector.', source: 'Livemint', sentiment: 'positive', score: 50, publishedAt: new Date(Date.now() - 86400000).toISOString() },
  { id: 'sa9', title: 'ICICI Bank Profit Jumps 16% — Best in Banking Cohort', summary: 'ICICI Bank reports highest-ever quarterly profit driven by retail loan growth and lower provisions.', source: 'ET Markets', sentiment: 'positive', score: 80, publishedAt: new Date(Date.now() - 14400000).toISOString() },
  { id: 'sa10', title: 'Banking Sector Outlook — RBI Status Quo Supports Credit Growth', summary: 'Analysts maintain positive outlook on banking sector as RBI maintains accommodative stance.', source: 'The Hindu Business Line', sentiment: 'positive', score: 40, publishedAt: new Date(Date.now() - 28800000).toISOString() },
  { id: 'sa11', title: 'SBIN Asset Quality Improves — GNPA Drops to 2.0%', summary: 'State Bank of India reports improving asset quality metrics with lower slippages.', source: 'Moneycontrol', sentiment: 'positive', score: 45, publishedAt: new Date(Date.now() - 57600000).toISOString() },
  { id: 'sa12', title: 'PSU Banks Rally — Nifty PSU Bank Index Up 3%', summary: 'PSU banking stocks rally on strong Q4 results and improving asset quality across the board.', source: 'CNBC TV18', sentiment: 'positive', score: 55, publishedAt: new Date(Date.now() - 7200000).toISOString() },
];

export const mockSentimentData: StockSentiment[] = [
  {
    symbol: 'RELIANCE',
    name: 'Reliance Industries Ltd.',
    sector: 'Energy',
    currentScore: 52,
    previousScore: 38,
    scoreChange: 14,
    label: 'bullish',
    confidence: 82,
    sourceBreakdown: { newsScore: 58, socialScore: 42, analystScore: 65, aiScore: 48 },
    history: generateSentimentHistory(45, 'RELIANCE'),
    recentArticles: sentimentArticles.filter(a => ['sa1', 'sa2', 'sa3'].includes(a.id)),
    topKeywords: ['growth', 'profit', 'beat', 'retail', 'expansion', 'subscribers'],
    mentionVolume: 2840,
    mentionChange: 15.3,
  },
  {
    symbol: 'HDFCBANK',
    name: 'HDFC Bank Ltd.',
    sector: 'Finance',
    currentScore: 68,
    previousScore: 55,
    scoreChange: 13,
    label: 'bullish',
    confidence: 88,
    sourceBreakdown: { newsScore: 72, socialScore: 55, analystScore: 78, aiScore: 62 },
    history: generateSentimentHistory(60, 'HDFCBANK'),
    recentArticles: sentimentArticles.filter(a => ['sa4', 'sa5'].includes(a.id)),
    topKeywords: ['profit', 'growth', 'margin', 'merger', 'asset', 'credit'],
    mentionVolume: 3650,
    mentionChange: 22.1,
  },
  {
    symbol: 'TCS',
    name: 'Tata Consultancy Services',
    sector: 'Technology',
    currentScore: 18,
    previousScore: 25,
    scoreChange: -7,
    label: 'neutral',
    confidence: 65,
    sourceBreakdown: { newsScore: 22, socialScore: 10, analystScore: 30, aiScore: 15 },
    history: generateSentimentHistory(22, 'TCS'),
    recentArticles: sentimentArticles.filter(a => ['sa6', 'sa7'].includes(a.id)),
    topKeywords: ['deal', 'cloud', 'spending', 'headwinds', 'digital'],
    mentionVolume: 2100,
    mentionChange: -5.2,
  },
  {
    symbol: 'INFY',
    name: 'Infosys Ltd.',
    sector: 'Technology',
    currentScore: 28,
    previousScore: 32,
    scoreChange: -4,
    label: 'neutral',
    confidence: 62,
    sourceBreakdown: { newsScore: 32, socialScore: 18, analystScore: 35, aiScore: 25 },
    history: generateSentimentHistory(30, 'INFY'),
    recentArticles: sentimentArticles.filter(a => ['sa8'].includes(a.id)),
    topKeywords: ['ai', 'pipeline', 'deals', 'cloud', 'digital'],
    mentionVolume: 1850,
    mentionChange: 8.7,
  },
  {
    symbol: 'ICICIBANK',
    name: 'ICICI Bank Ltd.',
    sector: 'Finance',
    currentScore: 72,
    previousScore: 58,
    scoreChange: 14,
    label: 'bullish',
    confidence: 90,
    sourceBreakdown: { newsScore: 75, socialScore: 60, analystScore: 80, aiScore: 68 },
    history: generateSentimentHistory(65, 'ICICIBANK'),
    recentArticles: sentimentArticles.filter(a => ['sa9', 'sa10'].includes(a.id)),
    topKeywords: ['profit', 'growth', 'loan', 'retail', 'banking', 'NIM'],
    mentionVolume: 2900,
    mentionChange: 18.5,
  },
  {
    symbol: 'SBIN',
    name: 'State Bank of India',
    sector: 'Finance',
    currentScore: 35,
    previousScore: 28,
    scoreChange: 7,
    label: 'neutral',
    confidence: 72,
    sourceBreakdown: { newsScore: 38, socialScore: 28, analystScore: 42, aiScore: 32 },
    history: generateSentimentHistory(30, 'SBIN'),
    recentArticles: sentimentArticles.filter(a => ['sa11', 'sa12'].includes(a.id)),
    topKeywords: ['PSU', 'rally', 'asset', 'quality', 'profit', 'NPA'],
    mentionVolume: 1680,
    mentionChange: 12.3,
  },
];

export const generateChartData = (days: number = 365, basePrice: number = 2500) => {
  const data: { date: string; price: number }[] = [];
  let currentPrice = basePrice;
  const today = new Date();
  
  for (let i = days; i >= 0; i--) {
    const date = new Date(today);
    date.setDate(date.getDate() - i);
    if (date.getDay() === 0 || date.getDay() === 6) continue;
    
    const change = (Math.random() - 0.48) * currentPrice * 0.03;
    currentPrice = Math.max(currentPrice + change, basePrice * 0.7);
    data.push({
      date: date.toISOString().split('T')[0],
      price: Math.round(currentPrice * 100) / 100,
    });
  }
  return data;
};



// ============ Stock History Generators ============

export const generateStockHistory = (basePrice: number = 2800) => {
  const data: { date: string; open: number; high: number; low: number; close: number; volume: number }[] = [];
  let price = basePrice;
  const today = new Date();
  
  for (let i = 365; i >= 0; i--) {
    const date = new Date(today);
    date.setDate(date.getDate() - i);
    if (date.getDay() === 0 || date.getDay() === 6) continue;
    
    const change = (Math.random() - 0.47) * price * 0.025;
    const open = price;
    const close = Math.max(open + change, open * 0.85);
    const high = Math.max(open, close) * (1 + Math.random() * 0.02);
    const low = Math.min(open, close) * (1 - Math.random() * 0.02);
    price = close;
    
    data.push({
      date: date.toISOString().split('T')[0],
      open: Math.round(open * 100) / 100,
      high: Math.round(high * 100) / 100,
      low: Math.round(low * 100) / 100,
      close: Math.round(close * 100) / 100,
      volume: Math.floor(Math.random() * 20000000) + 5000000,
    });
  }
  return data;
};

export const generateIntradayData = (minInterval: number = 1): { date: string; open: number; high: number; low: number; close: number; volume: number }[] => {
  const data: any[] = [];
  let price = 2800;
  const today = new Date();
  // Indian market session: 9:15 AM to 3:30 PM (375 minutes)
  const sessionStart = 9 * 60 + 15; // 9:15 AM in minutes
  const sessionEnd = 15 * 60 + 30;  // 3:30 PM in minutes
  const totalMinutes = sessionEnd - sessionStart; // 375 minutes
  const bars = Math.floor(totalMinutes / minInterval);
  
  for (let i = 0; i < bars; i++) {
    const minutesFromStart = i * minInterval;
    const hours = Math.floor((sessionStart + minutesFromStart) / 60);
    const mins = (sessionStart + minutesFromStart) % 60;
    
    const date = new Date(today);
    date.setHours(hours, mins, 0, 0);
    
    // More volatile intraday moves
    const change = (Math.random() - 0.5) * price * 0.008;
    const open = price;
    const close = Math.max(open + change, open * 0.95);
    const high = Math.max(open, close) * (1 + Math.random() * 0.015);
    const low = Math.min(open, close) * (1 - Math.random() * 0.015);
    price = close;
    
    data.push({
      date: date.toISOString(),
      open: Math.round(open * 100) / 100,
      high: Math.round(high * 100) / 100,
      low: Math.round(low * 100) / 100,
      close: Math.round(close * 100) / 100,
      volume: Math.floor(Math.random() * 5000000) + 500000,
    });
  }
  return data;
};
